all:
	cd src && $(MAKE)
check_hax:
	cd src && $(MAKE) check_hax
qemu:
	cd src && $(MAKE) qemu
skin_client:
	cd src && $(MAKE) skin_client
clean:
	cd src && $(MAKE) clean
distclean:
	cd src && $(MAKE) distclean
install:
	cd src && $(MAKE) install
