qemu:
	cd src && $(MAKE) qemu
skin_client:
	cd src && $(MAKE) skin_client
clean:
	cd src && $(MAKE) clean
distclean:
	cd src && $(MAKE) distclean
all:
	cd src && $(MAKE)
install:
	cd src && $(MAKE) install
