/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "ecs.pb-c.h"
void   ecs__check_version_req__init
                     (ECS__CheckVersionReq         *message)
{
  static ECS__CheckVersionReq init_value = ECS__CHECK_VERSION_REQ__INIT;
  *message = init_value;
}
size_t ecs__check_version_req__get_packed_size
                     (const ECS__CheckVersionReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__check_version_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__check_version_req__pack
                     (const ECS__CheckVersionReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__check_version_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__check_version_req__pack_to_buffer
                     (const ECS__CheckVersionReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__check_version_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__CheckVersionReq *
       ecs__check_version_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__CheckVersionReq *)
     protobuf_c_message_unpack (&ecs__check_version_req__descriptor,
                                allocator, len, data);
}
void   ecs__check_version_req__free_unpacked
                     (ECS__CheckVersionReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__check_version_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__check_version_ans__init
                     (ECS__CheckVersionAns         *message)
{
  static ECS__CheckVersionAns init_value = ECS__CHECK_VERSION_ANS__INIT;
  *message = init_value;
}
size_t ecs__check_version_ans__get_packed_size
                     (const ECS__CheckVersionAns *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__check_version_ans__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__check_version_ans__pack
                     (const ECS__CheckVersionAns *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__check_version_ans__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__check_version_ans__pack_to_buffer
                     (const ECS__CheckVersionAns *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__check_version_ans__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__CheckVersionAns *
       ecs__check_version_ans__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__CheckVersionAns *)
     protobuf_c_message_unpack (&ecs__check_version_ans__descriptor,
                                allocator, len, data);
}
void   ecs__check_version_ans__free_unpacked
                     (ECS__CheckVersionAns *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__check_version_ans__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__keep_alive_req__init
                     (ECS__KeepAliveReq         *message)
{
  static ECS__KeepAliveReq init_value = ECS__KEEP_ALIVE_REQ__INIT;
  *message = init_value;
}
size_t ecs__keep_alive_req__get_packed_size
                     (const ECS__KeepAliveReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__keep_alive_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__keep_alive_req__pack
                     (const ECS__KeepAliveReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__keep_alive_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__keep_alive_req__pack_to_buffer
                     (const ECS__KeepAliveReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__keep_alive_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__KeepAliveReq *
       ecs__keep_alive_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__KeepAliveReq *)
     protobuf_c_message_unpack (&ecs__keep_alive_req__descriptor,
                                allocator, len, data);
}
void   ecs__keep_alive_req__free_unpacked
                     (ECS__KeepAliveReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__keep_alive_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__keep_alive_ans__init
                     (ECS__KeepAliveAns         *message)
{
  static ECS__KeepAliveAns init_value = ECS__KEEP_ALIVE_ANS__INIT;
  *message = init_value;
}
size_t ecs__keep_alive_ans__get_packed_size
                     (const ECS__KeepAliveAns *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__keep_alive_ans__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__keep_alive_ans__pack
                     (const ECS__KeepAliveAns *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__keep_alive_ans__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__keep_alive_ans__pack_to_buffer
                     (const ECS__KeepAliveAns *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__keep_alive_ans__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__KeepAliveAns *
       ecs__keep_alive_ans__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__KeepAliveAns *)
     protobuf_c_message_unpack (&ecs__keep_alive_ans__descriptor,
                                allocator, len, data);
}
void   ecs__keep_alive_ans__free_unpacked
                     (ECS__KeepAliveAns *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__keep_alive_ans__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__start_req__init
                     (ECS__StartReq         *message)
{
  static ECS__StartReq init_value = ECS__START_REQ__INIT;
  *message = init_value;
}
size_t ecs__start_req__get_packed_size
                     (const ECS__StartReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__start_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__start_req__pack
                     (const ECS__StartReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__start_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__start_req__pack_to_buffer
                     (const ECS__StartReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__start_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__StartReq *
       ecs__start_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__StartReq *)
     protobuf_c_message_unpack (&ecs__start_req__descriptor,
                                allocator, len, data);
}
void   ecs__start_req__free_unpacked
                     (ECS__StartReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__start_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__start_ans__init
                     (ECS__StartAns         *message)
{
  static ECS__StartAns init_value = ECS__START_ANS__INIT;
  *message = init_value;
}
size_t ecs__start_ans__get_packed_size
                     (const ECS__StartAns *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__start_ans__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__start_ans__pack
                     (const ECS__StartAns *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__start_ans__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__start_ans__pack_to_buffer
                     (const ECS__StartAns *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__start_ans__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__StartAns *
       ecs__start_ans__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__StartAns *)
     protobuf_c_message_unpack (&ecs__start_ans__descriptor,
                                allocator, len, data);
}
void   ecs__start_ans__free_unpacked
                     (ECS__StartAns *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__start_ans__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__injector_req__init
                     (ECS__InjectorReq         *message)
{
  static ECS__InjectorReq init_value = ECS__INJECTOR_REQ__INIT;
  *message = init_value;
}
size_t ecs__injector_req__get_packed_size
                     (const ECS__InjectorReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__injector_req__pack
                     (const ECS__InjectorReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__injector_req__pack_to_buffer
                     (const ECS__InjectorReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__InjectorReq *
       ecs__injector_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__InjectorReq *)
     protobuf_c_message_unpack (&ecs__injector_req__descriptor,
                                allocator, len, data);
}
void   ecs__injector_req__free_unpacked
                     (ECS__InjectorReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__injector_ans__init
                     (ECS__InjectorAns         *message)
{
  static ECS__InjectorAns init_value = ECS__INJECTOR_ANS__INIT;
  *message = init_value;
}
size_t ecs__injector_ans__get_packed_size
                     (const ECS__InjectorAns *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_ans__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__injector_ans__pack
                     (const ECS__InjectorAns *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_ans__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__injector_ans__pack_to_buffer
                     (const ECS__InjectorAns *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_ans__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__InjectorAns *
       ecs__injector_ans__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__InjectorAns *)
     protobuf_c_message_unpack (&ecs__injector_ans__descriptor,
                                allocator, len, data);
}
void   ecs__injector_ans__free_unpacked
                     (ECS__InjectorAns *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_ans__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__injector_ntf__init
                     (ECS__InjectorNtf         *message)
{
  static ECS__InjectorNtf init_value = ECS__INJECTOR_NTF__INIT;
  *message = init_value;
}
size_t ecs__injector_ntf__get_packed_size
                     (const ECS__InjectorNtf *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_ntf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__injector_ntf__pack
                     (const ECS__InjectorNtf *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_ntf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__injector_ntf__pack_to_buffer
                     (const ECS__InjectorNtf *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_ntf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__InjectorNtf *
       ecs__injector_ntf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__InjectorNtf *)
     protobuf_c_message_unpack (&ecs__injector_ntf__descriptor,
                                allocator, len, data);
}
void   ecs__injector_ntf__free_unpacked
                     (ECS__InjectorNtf *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__injector_ntf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__device_req__init
                     (ECS__DeviceReq         *message)
{
  static ECS__DeviceReq init_value = ECS__DEVICE_REQ__INIT;
  *message = init_value;
}
size_t ecs__device_req__get_packed_size
                     (const ECS__DeviceReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__device_req__pack
                     (const ECS__DeviceReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__device_req__pack_to_buffer
                     (const ECS__DeviceReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__DeviceReq *
       ecs__device_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__DeviceReq *)
     protobuf_c_message_unpack (&ecs__device_req__descriptor,
                                allocator, len, data);
}
void   ecs__device_req__free_unpacked
                     (ECS__DeviceReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__device_ans__init
                     (ECS__DeviceAns         *message)
{
  static ECS__DeviceAns init_value = ECS__DEVICE_ANS__INIT;
  *message = init_value;
}
size_t ecs__device_ans__get_packed_size
                     (const ECS__DeviceAns *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_ans__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__device_ans__pack
                     (const ECS__DeviceAns *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_ans__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__device_ans__pack_to_buffer
                     (const ECS__DeviceAns *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_ans__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__DeviceAns *
       ecs__device_ans__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__DeviceAns *)
     protobuf_c_message_unpack (&ecs__device_ans__descriptor,
                                allocator, len, data);
}
void   ecs__device_ans__free_unpacked
                     (ECS__DeviceAns *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_ans__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__device_ntf__init
                     (ECS__DeviceNtf         *message)
{
  static ECS__DeviceNtf init_value = ECS__DEVICE_NTF__INIT;
  *message = init_value;
}
size_t ecs__device_ntf__get_packed_size
                     (const ECS__DeviceNtf *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_ntf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__device_ntf__pack
                     (const ECS__DeviceNtf *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_ntf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__device_ntf__pack_to_buffer
                     (const ECS__DeviceNtf *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_ntf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__DeviceNtf *
       ecs__device_ntf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__DeviceNtf *)
     protobuf_c_message_unpack (&ecs__device_ntf__descriptor,
                                allocator, len, data);
}
void   ecs__device_ntf__free_unpacked
                     (ECS__DeviceNtf *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__device_ntf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__host_keyboard_req__init
                     (ECS__HostKeyboardReq         *message)
{
  static ECS__HostKeyboardReq init_value = ECS__HOST_KEYBOARD_REQ__INIT;
  *message = init_value;
}
size_t ecs__host_keyboard_req__get_packed_size
                     (const ECS__HostKeyboardReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__host_keyboard_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__host_keyboard_req__pack
                     (const ECS__HostKeyboardReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__host_keyboard_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__host_keyboard_req__pack_to_buffer
                     (const ECS__HostKeyboardReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__host_keyboard_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__HostKeyboardReq *
       ecs__host_keyboard_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__HostKeyboardReq *)
     protobuf_c_message_unpack (&ecs__host_keyboard_req__descriptor,
                                allocator, len, data);
}
void   ecs__host_keyboard_req__free_unpacked
                     (ECS__HostKeyboardReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__host_keyboard_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__host_keyboard_ntf__init
                     (ECS__HostKeyboardNtf         *message)
{
  static ECS__HostKeyboardNtf init_value = ECS__HOST_KEYBOARD_NTF__INIT;
  *message = init_value;
}
size_t ecs__host_keyboard_ntf__get_packed_size
                     (const ECS__HostKeyboardNtf *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__host_keyboard_ntf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__host_keyboard_ntf__pack
                     (const ECS__HostKeyboardNtf *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__host_keyboard_ntf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__host_keyboard_ntf__pack_to_buffer
                     (const ECS__HostKeyboardNtf *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__host_keyboard_ntf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__HostKeyboardNtf *
       ecs__host_keyboard_ntf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__HostKeyboardNtf *)
     protobuf_c_message_unpack (&ecs__host_keyboard_ntf__descriptor,
                                allocator, len, data);
}
void   ecs__host_keyboard_ntf__free_unpacked
                     (ECS__HostKeyboardNtf *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__host_keyboard_ntf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__control_msg__init
                     (ECS__ControlMsg         *message)
{
  static ECS__ControlMsg init_value = ECS__CONTROL_MSG__INIT;
  *message = init_value;
}
size_t ecs__control_msg__get_packed_size
                     (const ECS__ControlMsg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__control_msg__pack
                     (const ECS__ControlMsg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__control_msg__pack_to_buffer
                     (const ECS__ControlMsg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__ControlMsg *
       ecs__control_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__ControlMsg *)
     protobuf_c_message_unpack (&ecs__control_msg__descriptor,
                                allocator, len, data);
}
void   ecs__control_msg__free_unpacked
                     (ECS__ControlMsg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__control_ans__init
                     (ECS__ControlAns         *message)
{
  static ECS__ControlAns init_value = ECS__CONTROL_ANS__INIT;
  *message = init_value;
}
size_t ecs__control_ans__get_packed_size
                     (const ECS__ControlAns *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_ans__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__control_ans__pack
                     (const ECS__ControlAns *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_ans__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__control_ans__pack_to_buffer
                     (const ECS__ControlAns *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_ans__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__ControlAns *
       ecs__control_ans__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__ControlAns *)
     protobuf_c_message_unpack (&ecs__control_ans__descriptor,
                                allocator, len, data);
}
void   ecs__control_ans__free_unpacked
                     (ECS__ControlAns *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_ans__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__control_ntf__init
                     (ECS__ControlNtf         *message)
{
  static ECS__ControlNtf init_value = ECS__CONTROL_NTF__INIT;
  *message = init_value;
}
size_t ecs__control_ntf__get_packed_size
                     (const ECS__ControlNtf *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_ntf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__control_ntf__pack
                     (const ECS__ControlNtf *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_ntf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__control_ntf__pack_to_buffer
                     (const ECS__ControlNtf *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_ntf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__ControlNtf *
       ecs__control_ntf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__ControlNtf *)
     protobuf_c_message_unpack (&ecs__control_ntf__descriptor,
                                allocator, len, data);
}
void   ecs__control_ntf__free_unpacked
                     (ECS__ControlNtf *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__control_ntf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__monitor_req__init
                     (ECS__MonitorReq         *message)
{
  static ECS__MonitorReq init_value = ECS__MONITOR_REQ__INIT;
  *message = init_value;
}
size_t ecs__monitor_req__get_packed_size
                     (const ECS__MonitorReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__monitor_req__pack
                     (const ECS__MonitorReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__monitor_req__pack_to_buffer
                     (const ECS__MonitorReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__MonitorReq *
       ecs__monitor_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__MonitorReq *)
     protobuf_c_message_unpack (&ecs__monitor_req__descriptor,
                                allocator, len, data);
}
void   ecs__monitor_req__free_unpacked
                     (ECS__MonitorReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__monitor_ans__init
                     (ECS__MonitorAns         *message)
{
  static ECS__MonitorAns init_value = ECS__MONITOR_ANS__INIT;
  *message = init_value;
}
size_t ecs__monitor_ans__get_packed_size
                     (const ECS__MonitorAns *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_ans__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__monitor_ans__pack
                     (const ECS__MonitorAns *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_ans__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__monitor_ans__pack_to_buffer
                     (const ECS__MonitorAns *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_ans__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__MonitorAns *
       ecs__monitor_ans__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__MonitorAns *)
     protobuf_c_message_unpack (&ecs__monitor_ans__descriptor,
                                allocator, len, data);
}
void   ecs__monitor_ans__free_unpacked
                     (ECS__MonitorAns *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_ans__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__monitor_ntf__init
                     (ECS__MonitorNtf         *message)
{
  static ECS__MonitorNtf init_value = ECS__MONITOR_NTF__INIT;
  *message = init_value;
}
size_t ecs__monitor_ntf__get_packed_size
                     (const ECS__MonitorNtf *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_ntf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__monitor_ntf__pack
                     (const ECS__MonitorNtf *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_ntf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__monitor_ntf__pack_to_buffer
                     (const ECS__MonitorNtf *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_ntf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__MonitorNtf *
       ecs__monitor_ntf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__MonitorNtf *)
     protobuf_c_message_unpack (&ecs__monitor_ntf__descriptor,
                                allocator, len, data);
}
void   ecs__monitor_ntf__free_unpacked
                     (ECS__MonitorNtf *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__monitor_ntf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__screen_dump_req__init
                     (ECS__ScreenDumpReq         *message)
{
  static ECS__ScreenDumpReq init_value = ECS__SCREEN_DUMP_REQ__INIT;
  *message = init_value;
}
size_t ecs__screen_dump_req__get_packed_size
                     (const ECS__ScreenDumpReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__screen_dump_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__screen_dump_req__pack
                     (const ECS__ScreenDumpReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__screen_dump_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__screen_dump_req__pack_to_buffer
                     (const ECS__ScreenDumpReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__screen_dump_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__ScreenDumpReq *
       ecs__screen_dump_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__ScreenDumpReq *)
     protobuf_c_message_unpack (&ecs__screen_dump_req__descriptor,
                                allocator, len, data);
}
void   ecs__screen_dump_req__free_unpacked
                     (ECS__ScreenDumpReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__screen_dump_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__screen_dump_ans__init
                     (ECS__ScreenDumpAns         *message)
{
  static ECS__ScreenDumpAns init_value = ECS__SCREEN_DUMP_ANS__INIT;
  *message = init_value;
}
size_t ecs__screen_dump_ans__get_packed_size
                     (const ECS__ScreenDumpAns *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__screen_dump_ans__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__screen_dump_ans__pack
                     (const ECS__ScreenDumpAns *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__screen_dump_ans__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__screen_dump_ans__pack_to_buffer
                     (const ECS__ScreenDumpAns *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__screen_dump_ans__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__ScreenDumpAns *
       ecs__screen_dump_ans__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__ScreenDumpAns *)
     protobuf_c_message_unpack (&ecs__screen_dump_ans__descriptor,
                                allocator, len, data);
}
void   ecs__screen_dump_ans__free_unpacked
                     (ECS__ScreenDumpAns *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__screen_dump_ans__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecs__master__init
                     (ECS__Master         *message)
{
  static ECS__Master init_value = ECS__MASTER__INIT;
  *message = init_value;
}
size_t ecs__master__get_packed_size
                     (const ECS__Master *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__master__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecs__master__pack
                     (const ECS__Master *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__master__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecs__master__pack_to_buffer
                     (const ECS__Master *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__master__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ECS__Master *
       ecs__master__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ECS__Master *)
     protobuf_c_message_unpack (&ecs__master__descriptor,
                                allocator, len, data);
}
void   ecs__master__free_unpacked
                     (ECS__Master *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ecs__master__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ecs__check_version_req__field_descriptors[1] =
{
  {
    "version_str",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__CheckVersionReq, version_str),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__check_version_req__field_indices_by_name[] = {
  0,   /* field[0] = version_str */
};
static const ProtobufCIntRange ecs__check_version_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ecs__check_version_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.CheckVersionReq",
  "CheckVersionReq",
  "ECS__CheckVersionReq",
  "ECS",
  sizeof(ECS__CheckVersionReq),
  1,
  ecs__check_version_req__field_descriptors,
  ecs__check_version_req__field_indices_by_name,
  1,  ecs__check_version_req__number_ranges,
  (ProtobufCMessageInit) ecs__check_version_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__check_version_ans__field_descriptors[2] =
{
  {
    "errcode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__CheckVersionAns, errcode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version_str",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__CheckVersionAns, version_str),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__check_version_ans__field_indices_by_name[] = {
  0,   /* field[0] = errcode */
  1,   /* field[1] = version_str */
};
static const ProtobufCIntRange ecs__check_version_ans__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ecs__check_version_ans__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.CheckVersionAns",
  "CheckVersionAns",
  "ECS__CheckVersionAns",
  "ECS",
  sizeof(ECS__CheckVersionAns),
  2,
  ecs__check_version_ans__field_descriptors,
  ecs__check_version_ans__field_indices_by_name,
  1,  ecs__check_version_ans__number_ranges,
  (ProtobufCMessageInit) ecs__check_version_ans__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__keep_alive_req__field_descriptors[1] =
{
  {
    "time_str",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__KeepAliveReq, time_str),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__keep_alive_req__field_indices_by_name[] = {
  0,   /* field[0] = time_str */
};
static const ProtobufCIntRange ecs__keep_alive_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ecs__keep_alive_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.KeepAliveReq",
  "KeepAliveReq",
  "ECS__KeepAliveReq",
  "ECS",
  sizeof(ECS__KeepAliveReq),
  1,
  ecs__keep_alive_req__field_descriptors,
  ecs__keep_alive_req__field_indices_by_name,
  1,  ecs__keep_alive_req__number_ranges,
  (ProtobufCMessageInit) ecs__keep_alive_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__keep_alive_ans__field_descriptors[1] =
{
  {
    "time_str",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__KeepAliveAns, time_str),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__keep_alive_ans__field_indices_by_name[] = {
  0,   /* field[0] = time_str */
};
static const ProtobufCIntRange ecs__keep_alive_ans__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ecs__keep_alive_ans__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.KeepAliveAns",
  "KeepAliveAns",
  "ECS__KeepAliveAns",
  "ECS",
  sizeof(ECS__KeepAliveAns),
  1,
  ecs__keep_alive_ans__field_descriptors,
  ecs__keep_alive_ans__field_indices_by_name,
  1,  ecs__keep_alive_ans__number_ranges,
  (ProtobufCMessageInit) ecs__keep_alive_ans__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__start_req__field_descriptors[0] =
{
};
static const unsigned ecs__start_req__field_indices_by_name[] = {
};
#define ecs__start_req__number_ranges NULL
const ProtobufCMessageDescriptor ecs__start_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.StartReq",
  "StartReq",
  "ECS__StartReq",
  "ECS",
  sizeof(ECS__StartReq),
  0,
  ecs__start_req__field_descriptors,
  ecs__start_req__field_indices_by_name,
  0,  ecs__start_req__number_ranges,
  (ProtobufCMessageInit) ecs__start_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__start_ans__field_descriptors[3] =
{
  {
    "host_keyboard_onoff",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ECS__StartAns, has_host_keyboard_onoff),
    PROTOBUF_C_OFFSETOF(ECS__StartAns, host_keyboard_onoff),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "earjack_onoff",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ECS__StartAns, has_earjack_onoff),
    PROTOBUF_C_OFFSETOF(ECS__StartAns, earjack_onoff),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera_onoff",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ECS__StartAns, has_camera_onoff),
    PROTOBUF_C_OFFSETOF(ECS__StartAns, camera_onoff),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__start_ans__field_indices_by_name[] = {
  2,   /* field[2] = camera_onoff */
  1,   /* field[1] = earjack_onoff */
  0,   /* field[0] = host_keyboard_onoff */
};
static const ProtobufCIntRange ecs__start_ans__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ecs__start_ans__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.StartAns",
  "StartAns",
  "ECS__StartAns",
  "ECS",
  sizeof(ECS__StartAns),
  3,
  ecs__start_ans__field_descriptors,
  ecs__start_ans__field_indices_by_name,
  1,  ecs__start_ans__number_ranges,
  (ProtobufCMessageInit) ecs__start_ans__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__injector_req__field_descriptors[5] =
{
  {
    "category",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorReq, category),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorReq, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorReq, group),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorReq, action),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(ECS__InjectorReq, has_data),
    PROTOBUF_C_OFFSETOF(ECS__InjectorReq, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__injector_req__field_indices_by_name[] = {
  3,   /* field[3] = action */
  0,   /* field[0] = category */
  4,   /* field[4] = data */
  2,   /* field[2] = group */
  1,   /* field[1] = length */
};
static const ProtobufCIntRange ecs__injector_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ecs__injector_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.InjectorReq",
  "InjectorReq",
  "ECS__InjectorReq",
  "ECS",
  sizeof(ECS__InjectorReq),
  5,
  ecs__injector_req__field_descriptors,
  ecs__injector_req__field_indices_by_name,
  1,  ecs__injector_req__number_ranges,
  (ProtobufCMessageInit) ecs__injector_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__injector_ans__field_descriptors[7] =
{
  {
    "errcode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorAns, errcode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errstr",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorAns, errstr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "category",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorAns, category),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorAns, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorAns, group),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorAns, action),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(ECS__InjectorAns, has_data),
    PROTOBUF_C_OFFSETOF(ECS__InjectorAns, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__injector_ans__field_indices_by_name[] = {
  5,   /* field[5] = action */
  2,   /* field[2] = category */
  6,   /* field[6] = data */
  0,   /* field[0] = errcode */
  1,   /* field[1] = errstr */
  4,   /* field[4] = group */
  3,   /* field[3] = length */
};
static const ProtobufCIntRange ecs__injector_ans__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ecs__injector_ans__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.InjectorAns",
  "InjectorAns",
  "ECS__InjectorAns",
  "ECS",
  sizeof(ECS__InjectorAns),
  7,
  ecs__injector_ans__field_descriptors,
  ecs__injector_ans__field_indices_by_name,
  1,  ecs__injector_ans__number_ranges,
  (ProtobufCMessageInit) ecs__injector_ans__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__injector_ntf__field_descriptors[5] =
{
  {
    "category",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorNtf, category),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorNtf, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorNtf, group),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__InjectorNtf, action),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(ECS__InjectorNtf, has_data),
    PROTOBUF_C_OFFSETOF(ECS__InjectorNtf, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__injector_ntf__field_indices_by_name[] = {
  3,   /* field[3] = action */
  0,   /* field[0] = category */
  4,   /* field[4] = data */
  2,   /* field[2] = group */
  1,   /* field[1] = length */
};
static const ProtobufCIntRange ecs__injector_ntf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ecs__injector_ntf__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.InjectorNtf",
  "InjectorNtf",
  "ECS__InjectorNtf",
  "ECS",
  sizeof(ECS__InjectorNtf),
  5,
  ecs__injector_ntf__field_descriptors,
  ecs__injector_ntf__field_indices_by_name,
  1,  ecs__injector_ntf__number_ranges,
  (ProtobufCMessageInit) ecs__injector_ntf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__device_req__field_descriptors[5] =
{
  {
    "category",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceReq, category),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceReq, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceReq, group),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceReq, action),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(ECS__DeviceReq, has_data),
    PROTOBUF_C_OFFSETOF(ECS__DeviceReq, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__device_req__field_indices_by_name[] = {
  3,   /* field[3] = action */
  0,   /* field[0] = category */
  4,   /* field[4] = data */
  2,   /* field[2] = group */
  1,   /* field[1] = length */
};
static const ProtobufCIntRange ecs__device_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ecs__device_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.DeviceReq",
  "DeviceReq",
  "ECS__DeviceReq",
  "ECS",
  sizeof(ECS__DeviceReq),
  5,
  ecs__device_req__field_descriptors,
  ecs__device_req__field_indices_by_name,
  1,  ecs__device_req__number_ranges,
  (ProtobufCMessageInit) ecs__device_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__device_ans__field_descriptors[7] =
{
  {
    "errcode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceAns, errcode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errstr",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceAns, errstr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "category",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceAns, category),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceAns, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceAns, group),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceAns, action),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(ECS__DeviceAns, has_data),
    PROTOBUF_C_OFFSETOF(ECS__DeviceAns, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__device_ans__field_indices_by_name[] = {
  5,   /* field[5] = action */
  2,   /* field[2] = category */
  6,   /* field[6] = data */
  0,   /* field[0] = errcode */
  1,   /* field[1] = errstr */
  4,   /* field[4] = group */
  3,   /* field[3] = length */
};
static const ProtobufCIntRange ecs__device_ans__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ecs__device_ans__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.DeviceAns",
  "DeviceAns",
  "ECS__DeviceAns",
  "ECS",
  sizeof(ECS__DeviceAns),
  7,
  ecs__device_ans__field_descriptors,
  ecs__device_ans__field_indices_by_name,
  1,  ecs__device_ans__number_ranges,
  (ProtobufCMessageInit) ecs__device_ans__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__device_ntf__field_descriptors[5] =
{
  {
    "category",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceNtf, category),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceNtf, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceNtf, group),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__DeviceNtf, action),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(ECS__DeviceNtf, has_data),
    PROTOBUF_C_OFFSETOF(ECS__DeviceNtf, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__device_ntf__field_indices_by_name[] = {
  3,   /* field[3] = action */
  0,   /* field[0] = category */
  4,   /* field[4] = data */
  2,   /* field[2] = group */
  1,   /* field[1] = length */
};
static const ProtobufCIntRange ecs__device_ntf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ecs__device_ntf__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.DeviceNtf",
  "DeviceNtf",
  "ECS__DeviceNtf",
  "ECS",
  sizeof(ECS__DeviceNtf),
  5,
  ecs__device_ntf__field_descriptors,
  ecs__device_ntf__field_indices_by_name,
  1,  ecs__device_ntf__number_ranges,
  (ProtobufCMessageInit) ecs__device_ntf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__host_keyboard_req__field_descriptors[1] =
{
  {
    "ison",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ECS__HostKeyboardReq, has_ison),
    PROTOBUF_C_OFFSETOF(ECS__HostKeyboardReq, ison),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__host_keyboard_req__field_indices_by_name[] = {
  0,   /* field[0] = ison */
};
static const ProtobufCIntRange ecs__host_keyboard_req__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ecs__host_keyboard_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.HostKeyboardReq",
  "HostKeyboardReq",
  "ECS__HostKeyboardReq",
  "ECS",
  sizeof(ECS__HostKeyboardReq),
  1,
  ecs__host_keyboard_req__field_descriptors,
  ecs__host_keyboard_req__field_indices_by_name,
  1,  ecs__host_keyboard_req__number_ranges,
  (ProtobufCMessageInit) ecs__host_keyboard_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__host_keyboard_ntf__field_descriptors[3] =
{
  {
    "errcode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__HostKeyboardNtf, errcode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errstr",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__HostKeyboardNtf, errstr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ison",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(ECS__HostKeyboardNtf, has_ison),
    PROTOBUF_C_OFFSETOF(ECS__HostKeyboardNtf, ison),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__host_keyboard_ntf__field_indices_by_name[] = {
  0,   /* field[0] = errcode */
  1,   /* field[1] = errstr */
  2,   /* field[2] = ison */
};
static const ProtobufCIntRange ecs__host_keyboard_ntf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ecs__host_keyboard_ntf__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.HostKeyboardNtf",
  "HostKeyboardNtf",
  "ECS__HostKeyboardNtf",
  "ECS",
  sizeof(ECS__HostKeyboardNtf),
  3,
  ecs__host_keyboard_ntf__field_descriptors,
  ecs__host_keyboard_ntf__field_indices_by_name,
  1,  ecs__host_keyboard_ntf__number_ranges,
  (ProtobufCMessageInit) ecs__host_keyboard_ntf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue ecs__control_msg__control_type__enum_values_by_number[2] =
{
  { "HOSTKEYBOARD_REQ", "ECS__CONTROL_MSG__CONTROL_TYPE__HOSTKEYBOARD_REQ", 2 },
  { "HOSTKEYBOARD_NTF", "ECS__CONTROL_MSG__CONTROL_TYPE__HOSTKEYBOARD_NTF", 3 },
};
static const ProtobufCIntRange ecs__control_msg__control_type__value_ranges[] = {
{2, 0},{0, 2}
};
const ProtobufCEnumValueIndex ecs__control_msg__control_type__enum_values_by_name[2] =
{
  { "HOSTKEYBOARD_NTF", 1 },
  { "HOSTKEYBOARD_REQ", 0 },
};
const ProtobufCEnumDescriptor ecs__control_msg__control_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "ECS.ControlMsg.ControlType",
  "ControlType",
  "ECS__ControlMsg__ControlType",
  "ECS",
  2,
  ecs__control_msg__control_type__enum_values_by_number,
  2,
  ecs__control_msg__control_type__enum_values_by_name,
  1,
  ecs__control_msg__control_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ecs__control_msg__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__ControlMsg, type),
    &ecs__control_msg__control_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostkeyboard_req",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__ControlMsg, hostkeyboard_req),
    &ecs__host_keyboard_req__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostkeyboard_ntf",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__ControlMsg, hostkeyboard_ntf),
    &ecs__host_keyboard_ntf__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__control_msg__field_indices_by_name[] = {
  2,   /* field[2] = hostkeyboard_ntf */
  1,   /* field[1] = hostkeyboard_req */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ecs__control_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ecs__control_msg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.ControlMsg",
  "ControlMsg",
  "ECS__ControlMsg",
  "ECS",
  sizeof(ECS__ControlMsg),
  3,
  ecs__control_msg__field_descriptors,
  ecs__control_msg__field_indices_by_name,
  1,  ecs__control_msg__number_ranges,
  (ProtobufCMessageInit) ecs__control_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__control_ans__field_descriptors[2] =
{
  {
    "errcode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__ControlAns, errcode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__ControlAns, errmsg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__control_ans__field_indices_by_name[] = {
  0,   /* field[0] = errcode */
  1,   /* field[1] = errmsg */
};
static const ProtobufCIntRange ecs__control_ans__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ecs__control_ans__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.ControlAns",
  "ControlAns",
  "ECS__ControlAns",
  "ECS",
  sizeof(ECS__ControlAns),
  2,
  ecs__control_ans__field_descriptors,
  ecs__control_ans__field_indices_by_name,
  1,  ecs__control_ans__number_ranges,
  (ProtobufCMessageInit) ecs__control_ans__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__control_ntf__field_descriptors[3] =
{
  {
    "category",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__ControlNtf, category),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__ControlNtf, command),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(ECS__ControlNtf, has_data),
    PROTOBUF_C_OFFSETOF(ECS__ControlNtf, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__control_ntf__field_indices_by_name[] = {
  0,   /* field[0] = category */
  1,   /* field[1] = command */
  2,   /* field[2] = data */
};
static const ProtobufCIntRange ecs__control_ntf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ecs__control_ntf__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.ControlNtf",
  "ControlNtf",
  "ECS__ControlNtf",
  "ECS",
  sizeof(ECS__ControlNtf),
  3,
  ecs__control_ntf__field_descriptors,
  ecs__control_ntf__field_indices_by_name,
  1,  ecs__control_ntf__number_ranges,
  (ProtobufCMessageInit) ecs__control_ntf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__monitor_req__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__MonitorReq, command),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__monitor_req__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange ecs__monitor_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ecs__monitor_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.MonitorReq",
  "MonitorReq",
  "ECS__MonitorReq",
  "ECS",
  sizeof(ECS__MonitorReq),
  1,
  ecs__monitor_req__field_descriptors,
  ecs__monitor_req__field_indices_by_name,
  1,  ecs__monitor_req__number_ranges,
  (ProtobufCMessageInit) ecs__monitor_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__monitor_ans__field_descriptors[4] =
{
  {
    "errcode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__MonitorAns, errcode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__MonitorAns, errmsg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__MonitorAns, command),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(ECS__MonitorAns, has_data),
    PROTOBUF_C_OFFSETOF(ECS__MonitorAns, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__monitor_ans__field_indices_by_name[] = {
  2,   /* field[2] = command */
  3,   /* field[3] = data */
  0,   /* field[0] = errcode */
  1,   /* field[1] = errmsg */
};
static const ProtobufCIntRange ecs__monitor_ans__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ecs__monitor_ans__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.MonitorAns",
  "MonitorAns",
  "ECS__MonitorAns",
  "ECS",
  sizeof(ECS__MonitorAns),
  4,
  ecs__monitor_ans__field_descriptors,
  ecs__monitor_ans__field_indices_by_name,
  1,  ecs__monitor_ans__number_ranges,
  (ProtobufCMessageInit) ecs__monitor_ans__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__monitor_ntf__field_descriptors[2] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__MonitorNtf, command),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(ECS__MonitorNtf, has_data),
    PROTOBUF_C_OFFSETOF(ECS__MonitorNtf, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__monitor_ntf__field_indices_by_name[] = {
  0,   /* field[0] = command */
  1,   /* field[1] = data */
};
static const ProtobufCIntRange ecs__monitor_ntf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ecs__monitor_ntf__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.MonitorNtf",
  "MonitorNtf",
  "ECS__MonitorNtf",
  "ECS",
  sizeof(ECS__MonitorNtf),
  2,
  ecs__monitor_ntf__field_descriptors,
  ecs__monitor_ntf__field_indices_by_name,
  1,  ecs__monitor_ntf__number_ranges,
  (ProtobufCMessageInit) ecs__monitor_ntf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__screen_dump_req__field_descriptors[1] =
{
  {
    "output_path",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__ScreenDumpReq, output_path),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__screen_dump_req__field_indices_by_name[] = {
  0,   /* field[0] = output_path */
};
static const ProtobufCIntRange ecs__screen_dump_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ecs__screen_dump_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.ScreenDumpReq",
  "ScreenDumpReq",
  "ECS__ScreenDumpReq",
  "ECS",
  sizeof(ECS__ScreenDumpReq),
  1,
  ecs__screen_dump_req__field_descriptors,
  ecs__screen_dump_req__field_indices_by_name,
  1,  ecs__screen_dump_req__number_ranges,
  (ProtobufCMessageInit) ecs__screen_dump_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecs__screen_dump_ans__field_descriptors[2] =
{
  {
    "errcode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__ScreenDumpAns, errcode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__ScreenDumpAns, errmsg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__screen_dump_ans__field_indices_by_name[] = {
  0,   /* field[0] = errcode */
  1,   /* field[1] = errmsg */
};
static const ProtobufCIntRange ecs__screen_dump_ans__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ecs__screen_dump_ans__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.ScreenDumpAns",
  "ScreenDumpAns",
  "ECS__ScreenDumpAns",
  "ECS",
  sizeof(ECS__ScreenDumpAns),
  2,
  ecs__screen_dump_ans__field_descriptors,
  ecs__screen_dump_ans__field_indices_by_name,
  1,  ecs__screen_dump_ans__number_ranges,
  (ProtobufCMessageInit) ecs__screen_dump_ans__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue ecs__master__type__enum_values_by_number[20] =
{
  { "CHECKVERSION_REQ", "ECS__MASTER__TYPE__CHECKVERSION_REQ", 2 },
  { "CHECKVERSION_ANS", "ECS__MASTER__TYPE__CHECKVERSION_ANS", 3 },
  { "KEEPALIVE_REQ", "ECS__MASTER__TYPE__KEEPALIVE_REQ", 4 },
  { "KEEPALIVE_ANS", "ECS__MASTER__TYPE__KEEPALIVE_ANS", 5 },
  { "START_REQ", "ECS__MASTER__TYPE__START_REQ", 6 },
  { "START_ANS", "ECS__MASTER__TYPE__START_ANS", 7 },
  { "INJECTOR_REQ", "ECS__MASTER__TYPE__INJECTOR_REQ", 8 },
  { "INJECTOR_ANS", "ECS__MASTER__TYPE__INJECTOR_ANS", 9 },
  { "INJECTOR_NTF", "ECS__MASTER__TYPE__INJECTOR_NTF", 10 },
  { "DEVICE_REQ", "ECS__MASTER__TYPE__DEVICE_REQ", 11 },
  { "DEVICE_ANS", "ECS__MASTER__TYPE__DEVICE_ANS", 12 },
  { "DEVICE_NTF", "ECS__MASTER__TYPE__DEVICE_NTF", 13 },
  { "CONTROL_MSG", "ECS__MASTER__TYPE__CONTROL_MSG", 14 },
  { "CONTROL_ANS", "ECS__MASTER__TYPE__CONTROL_ANS", 15 },
  { "CONTROL_NTF", "ECS__MASTER__TYPE__CONTROL_NTF", 16 },
  { "MONITOR_REQ", "ECS__MASTER__TYPE__MONITOR_REQ", 17 },
  { "MONITOR_ANS", "ECS__MASTER__TYPE__MONITOR_ANS", 18 },
  { "MONITOR_NTF", "ECS__MASTER__TYPE__MONITOR_NTF", 19 },
  { "SCREEN_DUMP_REQ", "ECS__MASTER__TYPE__SCREEN_DUMP_REQ", 20 },
  { "SCREEN_DUMP_ANS", "ECS__MASTER__TYPE__SCREEN_DUMP_ANS", 21 },
};
static const ProtobufCIntRange ecs__master__type__value_ranges[] = {
{2, 0},{0, 20}
};
const ProtobufCEnumValueIndex ecs__master__type__enum_values_by_name[20] =
{
  { "CHECKVERSION_ANS", 1 },
  { "CHECKVERSION_REQ", 0 },
  { "CONTROL_ANS", 13 },
  { "CONTROL_MSG", 12 },
  { "CONTROL_NTF", 14 },
  { "DEVICE_ANS", 10 },
  { "DEVICE_NTF", 11 },
  { "DEVICE_REQ", 9 },
  { "INJECTOR_ANS", 7 },
  { "INJECTOR_NTF", 8 },
  { "INJECTOR_REQ", 6 },
  { "KEEPALIVE_ANS", 3 },
  { "KEEPALIVE_REQ", 2 },
  { "MONITOR_ANS", 16 },
  { "MONITOR_NTF", 17 },
  { "MONITOR_REQ", 15 },
  { "SCREEN_DUMP_ANS", 19 },
  { "SCREEN_DUMP_REQ", 18 },
  { "START_ANS", 5 },
  { "START_REQ", 4 },
};
const ProtobufCEnumDescriptor ecs__master__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "ECS.Master.Type",
  "Type",
  "ECS__Master__Type",
  "ECS",
  20,
  ecs__master__type__enum_values_by_number,
  20,
  ecs__master__type__enum_values_by_name,
  1,
  ecs__master__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ecs__master__field_descriptors[21] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, type),
    &ecs__master__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checkversion_req",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, checkversion_req),
    &ecs__check_version_req__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checkversion_ans",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, checkversion_ans),
    &ecs__check_version_ans__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keepalive_req",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, keepalive_req),
    &ecs__keep_alive_req__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keepalive_ans",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, keepalive_ans),
    &ecs__keep_alive_ans__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_req",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, start_req),
    &ecs__start_req__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_ans",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, start_ans),
    &ecs__start_ans__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "injector_req",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, injector_req),
    &ecs__injector_req__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "injector_ans",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, injector_ans),
    &ecs__injector_ans__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "injector_ntf",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, injector_ntf),
    &ecs__injector_ntf__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_req",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, device_req),
    &ecs__device_req__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_ans",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, device_ans),
    &ecs__device_ans__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_ntf",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, device_ntf),
    &ecs__device_ntf__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "control_msg",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, control_msg),
    &ecs__control_msg__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "control_ans",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, control_ans),
    &ecs__control_ans__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "control_ntf",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, control_ntf),
    &ecs__control_ntf__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monitor_req",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, monitor_req),
    &ecs__monitor_req__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monitor_ans",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, monitor_ans),
    &ecs__monitor_ans__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monitor_ntf",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, monitor_ntf),
    &ecs__monitor_ntf__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "screen_dump_req",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, screen_dump_req),
    &ecs__screen_dump_req__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "screen_dump_ans",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ECS__Master, screen_dump_ans),
    &ecs__screen_dump_ans__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecs__master__field_indices_by_name[] = {
  2,   /* field[2] = checkversion_ans */
  1,   /* field[1] = checkversion_req */
  14,   /* field[14] = control_ans */
  13,   /* field[13] = control_msg */
  15,   /* field[15] = control_ntf */
  11,   /* field[11] = device_ans */
  12,   /* field[12] = device_ntf */
  10,   /* field[10] = device_req */
  8,   /* field[8] = injector_ans */
  9,   /* field[9] = injector_ntf */
  7,   /* field[7] = injector_req */
  4,   /* field[4] = keepalive_ans */
  3,   /* field[3] = keepalive_req */
  17,   /* field[17] = monitor_ans */
  18,   /* field[18] = monitor_ntf */
  16,   /* field[16] = monitor_req */
  20,   /* field[20] = screen_dump_ans */
  19,   /* field[19] = screen_dump_req */
  6,   /* field[6] = start_ans */
  5,   /* field[5] = start_req */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ecs__master__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 21 }
};
const ProtobufCMessageDescriptor ecs__master__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ECS.Master",
  "Master",
  "ECS__Master",
  "ECS",
  sizeof(ECS__Master),
  21,
  ecs__master__field_descriptors,
  ecs__master__field_indices_by_name,
  1,  ecs__master__number_ranges,
  (ProtobufCMessageInit) ecs__master__init,
  NULL,NULL,NULL    /* reserved[123] */
};
