/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_ecs_5fids_2eproto__INCLUDED
#define PROTOBUF_C_ecs_5fids_2eproto__INCLUDED

#include "../../../distrib/protobuf/protobuf-c.h"

PROTOBUF_C_BEGIN_DECLS




/* --- enums --- */

typedef enum _ECS__MasterType {
  ECS__MASTER__TYPE__CHECKVERSION_REQ = 2,
  ECS__MASTER__TYPE__CHECKVERSION_ANS = 3,
  ECS__MASTER__TYPE__KEEPALIVE_REQ = 4,
  ECS__MASTER__TYPE__KEEPALIVE_ANS = 5,
  ECS__MASTER__TYPE__INJECTOR_REQ = 6,
  ECS__MASTER__TYPE__INJECTOR_ANS = 7,
  ECS__MASTER__TYPE__INJECTOR_NTF = 8,
  ECS__MASTER__TYPE__DEVICE_REQ = 9,
  ECS__MASTER__TYPE__DEVICE_ANS = 10,
  ECS__MASTER__TYPE__DEVICE_NTF = 11,
  ECS__MASTER__TYPE__MONITOR_REQ = 12,
  ECS__MASTER__TYPE__MONITOR_ANS = 13,
  ECS__MASTER__TYPE__MONITOR_NTF = 14,
  ECS__MASTER__TYPE__NFC_REQ = 101,
  ECS__MASTER__TYPE__NFC_NTF = 102,
  ECS__MASTER__TYPE__TETHERING_REQ = 103,
  ECS__MASTER__TYPE__TETHERING_ANS = 104,
  ECS__MASTER__TYPE__TETHERING_NTF = 105
} ECS__MasterType;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    ecs__master__type__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_ecs_5fids_2eproto__INCLUDED */
