/*
 * Generated by gen-yagl-calls.py, do not modify!
 */
#include "yagl_gles2_calls.h"
#include "yagl_host_gles2_calls.h"
#include "yagl_transport_gl2.h"
#include "yagl_thread.h"
#include "yagl_process.h"
#include "yagl_log.h"

/*
 * glActiveTexture dispatcher. id = 1
 */
static bool yagl_func_glActiveTexture(struct yagl_transport *t)
{
    GLenum texture;
    texture = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glActiveTexture, GLenum, texture);
    (void)yagl_host_glActiveTexture(texture);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBindBuffer dispatcher. id = 2
 */
static bool yagl_func_glBindBuffer(struct yagl_transport *t)
{
    GLenum target;
    GLuint buffer;
    target = yagl_transport_get_out_GLenum(t);
    buffer = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBindBuffer, GLenum, GLuint, target, buffer);
    (void)yagl_host_glBindBuffer(target, buffer);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBindFramebuffer dispatcher. id = 3
 */
static bool yagl_func_glBindFramebuffer(struct yagl_transport *t)
{
    GLenum target;
    GLuint framebuffer;
    target = yagl_transport_get_out_GLenum(t);
    framebuffer = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBindFramebuffer, GLenum, GLuint, target, framebuffer);
    (void)yagl_host_glBindFramebuffer(target, framebuffer);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBindRenderbuffer dispatcher. id = 4
 */
static bool yagl_func_glBindRenderbuffer(struct yagl_transport *t)
{
    GLenum target;
    GLuint renderbuffer;
    target = yagl_transport_get_out_GLenum(t);
    renderbuffer = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBindRenderbuffer, GLenum, GLuint, target, renderbuffer);
    (void)yagl_host_glBindRenderbuffer(target, renderbuffer);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBindTexture dispatcher. id = 5
 */
static bool yagl_func_glBindTexture(struct yagl_transport *t)
{
    GLenum target;
    GLuint texture;
    target = yagl_transport_get_out_GLenum(t);
    texture = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBindTexture, GLenum, GLuint, target, texture);
    (void)yagl_host_glBindTexture(target, texture);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBlendEquation dispatcher. id = 6
 */
static bool yagl_func_glBlendEquation(struct yagl_transport *t)
{
    GLenum mode;
    mode = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glBlendEquation, GLenum, mode);
    (void)yagl_host_glBlendEquation(mode);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBlendEquationSeparate dispatcher. id = 7
 */
static bool yagl_func_glBlendEquationSeparate(struct yagl_transport *t)
{
    GLenum modeRGB;
    GLenum modeAlpha;
    modeRGB = yagl_transport_get_out_GLenum(t);
    modeAlpha = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBlendEquationSeparate, GLenum, GLenum, modeRGB, modeAlpha);
    (void)yagl_host_glBlendEquationSeparate(modeRGB, modeAlpha);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBlendFunc dispatcher. id = 8
 */
static bool yagl_func_glBlendFunc(struct yagl_transport *t)
{
    GLenum sfactor;
    GLenum dfactor;
    sfactor = yagl_transport_get_out_GLenum(t);
    dfactor = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBlendFunc, GLenum, GLenum, sfactor, dfactor);
    (void)yagl_host_glBlendFunc(sfactor, dfactor);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBlendFuncSeparate dispatcher. id = 9
 */
static bool yagl_func_glBlendFuncSeparate(struct yagl_transport *t)
{
    GLenum srcRGB;
    GLenum dstRGB;
    GLenum srcAlpha;
    GLenum dstAlpha;
    srcRGB = yagl_transport_get_out_GLenum(t);
    dstRGB = yagl_transport_get_out_GLenum(t);
    srcAlpha = yagl_transport_get_out_GLenum(t);
    dstAlpha = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glBlendFuncSeparate, GLenum, GLenum, GLenum, GLenum, srcRGB, dstRGB, srcAlpha, dstAlpha);
    (void)yagl_host_glBlendFuncSeparate(srcRGB, dstRGB, srcAlpha, dstAlpha);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBufferData dispatcher. id = 10
 */
static bool yagl_func_glBufferData(struct yagl_transport *t)
{
    GLenum target;
    const GLvoid *data;
    int32_t data_count;
    GLenum usage;
    target = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_out_array(t, 1, (const void**)&data, &data_count)) {
        return false;
    }
    usage = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glBufferData, GLenum, void*, GLenum, target, data, usage);
    (void)yagl_host_glBufferData(target, data, data_count, usage);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBufferSubData dispatcher. id = 11
 */
static bool yagl_func_glBufferSubData(struct yagl_transport *t)
{
    GLenum target;
    GLsizei offset;
    const GLvoid *data;
    int32_t data_count;
    target = yagl_transport_get_out_GLenum(t);
    offset = yagl_transport_get_out_GLsizei(t);
    if (!yagl_transport_get_out_array(t, 1, (const void**)&data, &data_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glBufferSubData, GLenum, GLsizei, void*, target, offset, data);
    (void)yagl_host_glBufferSubData(target, offset, data, data_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glCheckFramebufferStatus dispatcher. id = 12
 */
static bool yagl_func_glCheckFramebufferStatus(struct yagl_transport *t)
{
    GLenum target;
    GLenum *retval;
    target = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glCheckFramebufferStatus, GLenum, target);
    *retval = yagl_host_glCheckFramebufferStatus(target);
    YAGL_LOG_FUNC_EXIT_SPLIT(GLenum, *retval);

    return true;
}

/*
 * glClear dispatcher. id = 13
 */
static bool yagl_func_glClear(struct yagl_transport *t)
{
    GLbitfield mask;
    mask = yagl_transport_get_out_GLbitfield(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glClear, GLbitfield, mask);
    (void)yagl_host_glClear(mask);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glClearColor dispatcher. id = 14
 */
static bool yagl_func_glClearColor(struct yagl_transport *t)
{
    GLclampf red;
    GLclampf green;
    GLclampf blue;
    GLclampf alpha;
    red = yagl_transport_get_out_GLclampf(t);
    green = yagl_transport_get_out_GLclampf(t);
    blue = yagl_transport_get_out_GLclampf(t);
    alpha = yagl_transport_get_out_GLclampf(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glClearColor, GLclampf, GLclampf, GLclampf, GLclampf, red, green, blue, alpha);
    (void)yagl_host_glClearColor(red, green, blue, alpha);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glClearDepthf dispatcher. id = 15
 */
static bool yagl_func_glClearDepthf(struct yagl_transport *t)
{
    GLclampf depth;
    depth = yagl_transport_get_out_GLclampf(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glClearDepthf, GLclampf, depth);
    (void)yagl_host_glClearDepthf(depth);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glClearStencil dispatcher. id = 16
 */
static bool yagl_func_glClearStencil(struct yagl_transport *t)
{
    GLint s;
    s = yagl_transport_get_out_GLint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glClearStencil, GLint, s);
    (void)yagl_host_glClearStencil(s);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glColorMask dispatcher. id = 17
 */
static bool yagl_func_glColorMask(struct yagl_transport *t)
{
    GLboolean red;
    GLboolean green;
    GLboolean blue;
    GLboolean alpha;
    red = yagl_transport_get_out_GLboolean(t);
    green = yagl_transport_get_out_GLboolean(t);
    blue = yagl_transport_get_out_GLboolean(t);
    alpha = yagl_transport_get_out_GLboolean(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glColorMask, GLboolean, GLboolean, GLboolean, GLboolean, red, green, blue, alpha);
    (void)yagl_host_glColorMask(red, green, blue, alpha);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glCompressedTexImage2D dispatcher. id = 18
 */
static bool yagl_func_glCompressedTexImage2D(struct yagl_transport *t)
{
    GLenum target;
    GLint level;
    GLenum internalformat;
    GLsizei width;
    GLsizei height;
    GLint border;
    const GLvoid *data;
    int32_t data_count;
    target = yagl_transport_get_out_GLenum(t);
    level = yagl_transport_get_out_GLint(t);
    internalformat = yagl_transport_get_out_GLenum(t);
    width = yagl_transport_get_out_GLsizei(t);
    height = yagl_transport_get_out_GLsizei(t);
    border = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_out_array(t, 1, (const void**)&data, &data_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT7(glCompressedTexImage2D, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, void*, target, level, internalformat, width, height, border, data);
    (void)yagl_host_glCompressedTexImage2D(target, level, internalformat, width, height, border, data, data_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glCompressedTexSubImage2D dispatcher. id = 19
 */
static bool yagl_func_glCompressedTexSubImage2D(struct yagl_transport *t)
{
    GLenum target;
    GLint level;
    GLint xoffset;
    GLint yoffset;
    GLsizei width;
    GLsizei height;
    GLenum format;
    const GLvoid *data;
    int32_t data_count;
    target = yagl_transport_get_out_GLenum(t);
    level = yagl_transport_get_out_GLint(t);
    xoffset = yagl_transport_get_out_GLint(t);
    yoffset = yagl_transport_get_out_GLint(t);
    width = yagl_transport_get_out_GLsizei(t);
    height = yagl_transport_get_out_GLsizei(t);
    format = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_out_array(t, 1, (const void**)&data, &data_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT8(glCompressedTexSubImage2D, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, void*, target, level, xoffset, yoffset, width, height, format, data);
    (void)yagl_host_glCompressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, data, data_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glCopyTexImage2D dispatcher. id = 20
 */
static bool yagl_func_glCopyTexImage2D(struct yagl_transport *t)
{
    GLenum target;
    GLint level;
    GLenum internalformat;
    GLint x;
    GLint y;
    GLsizei width;
    GLsizei height;
    GLint border;
    target = yagl_transport_get_out_GLenum(t);
    level = yagl_transport_get_out_GLint(t);
    internalformat = yagl_transport_get_out_GLenum(t);
    x = yagl_transport_get_out_GLint(t);
    y = yagl_transport_get_out_GLint(t);
    width = yagl_transport_get_out_GLsizei(t);
    height = yagl_transport_get_out_GLsizei(t);
    border = yagl_transport_get_out_GLint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT8(glCopyTexImage2D, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint, target, level, internalformat, x, y, width, height, border);
    (void)yagl_host_glCopyTexImage2D(target, level, internalformat, x, y, width, height, border);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glCopyTexSubImage2D dispatcher. id = 21
 */
static bool yagl_func_glCopyTexSubImage2D(struct yagl_transport *t)
{
    GLenum target;
    GLint level;
    GLint xoffset;
    GLint yoffset;
    GLint x;
    GLint y;
    GLsizei width;
    GLsizei height;
    target = yagl_transport_get_out_GLenum(t);
    level = yagl_transport_get_out_GLint(t);
    xoffset = yagl_transport_get_out_GLint(t);
    yoffset = yagl_transport_get_out_GLint(t);
    x = yagl_transport_get_out_GLint(t);
    y = yagl_transport_get_out_GLint(t);
    width = yagl_transport_get_out_GLsizei(t);
    height = yagl_transport_get_out_GLsizei(t);
    YAGL_LOG_FUNC_ENTER_SPLIT8(glCopyTexSubImage2D, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, target, level, xoffset, yoffset, x, y, width, height);
    (void)yagl_host_glCopyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glCullFace dispatcher. id = 22
 */
static bool yagl_func_glCullFace(struct yagl_transport *t)
{
    GLenum mode;
    mode = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glCullFace, GLenum, mode);
    (void)yagl_host_glCullFace(mode);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDeleteBuffers dispatcher. id = 23
 */
static bool yagl_func_glDeleteBuffers(struct yagl_transport *t)
{
    const GLuint *buffers;
    int32_t buffers_count;
    if (!yagl_transport_get_out_array(t, sizeof(GLuint), (const void**)&buffers, &buffers_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDeleteBuffers, void*, buffers);
    (void)yagl_host_glDeleteBuffers(buffers, buffers_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDeleteFramebuffers dispatcher. id = 24
 */
static bool yagl_func_glDeleteFramebuffers(struct yagl_transport *t)
{
    const GLuint *framebuffers;
    int32_t framebuffers_count;
    if (!yagl_transport_get_out_array(t, sizeof(GLuint), (const void**)&framebuffers, &framebuffers_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDeleteFramebuffers, void*, framebuffers);
    (void)yagl_host_glDeleteFramebuffers(framebuffers, framebuffers_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDeleteRenderbuffers dispatcher. id = 25
 */
static bool yagl_func_glDeleteRenderbuffers(struct yagl_transport *t)
{
    const GLuint *renderbuffers;
    int32_t renderbuffers_count;
    if (!yagl_transport_get_out_array(t, sizeof(GLuint), (const void**)&renderbuffers, &renderbuffers_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDeleteRenderbuffers, void*, renderbuffers);
    (void)yagl_host_glDeleteRenderbuffers(renderbuffers, renderbuffers_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDeleteTextures dispatcher. id = 26
 */
static bool yagl_func_glDeleteTextures(struct yagl_transport *t)
{
    const GLuint *textures;
    int32_t textures_count;
    if (!yagl_transport_get_out_array(t, sizeof(GLuint), (const void**)&textures, &textures_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDeleteTextures, void*, textures);
    (void)yagl_host_glDeleteTextures(textures, textures_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDepthFunc dispatcher. id = 27
 */
static bool yagl_func_glDepthFunc(struct yagl_transport *t)
{
    GLenum func;
    func = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDepthFunc, GLenum, func);
    (void)yagl_host_glDepthFunc(func);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDepthMask dispatcher. id = 28
 */
static bool yagl_func_glDepthMask(struct yagl_transport *t)
{
    GLboolean flag;
    flag = yagl_transport_get_out_GLboolean(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDepthMask, GLboolean, flag);
    (void)yagl_host_glDepthMask(flag);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDepthRangef dispatcher. id = 29
 */
static bool yagl_func_glDepthRangef(struct yagl_transport *t)
{
    GLclampf zNear;
    GLclampf zFar;
    zNear = yagl_transport_get_out_GLclampf(t);
    zFar = yagl_transport_get_out_GLclampf(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glDepthRangef, GLclampf, GLclampf, zNear, zFar);
    (void)yagl_host_glDepthRangef(zNear, zFar);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDisable dispatcher. id = 30
 */
static bool yagl_func_glDisable(struct yagl_transport *t)
{
    GLenum cap;
    cap = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDisable, GLenum, cap);
    (void)yagl_host_glDisable(cap);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDrawArrays dispatcher. id = 31
 */
static bool yagl_func_glDrawArrays(struct yagl_transport *t)
{
    GLenum mode;
    GLint first;
    GLsizei count;
    mode = yagl_transport_get_out_GLenum(t);
    first = yagl_transport_get_out_GLint(t);
    count = yagl_transport_get_out_GLsizei(t);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glDrawArrays, GLenum, GLint, GLsizei, mode, first, count);
    (void)yagl_host_glDrawArrays(mode, first, count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glEGLImageTargetTexture2DOES dispatcher. id = 32
 */
static bool yagl_func_glEGLImageTargetTexture2DOES(struct yagl_transport *t)
{
    GLenum target;
    yagl_host_handle image;
    target = yagl_transport_get_out_GLenum(t);
    image = yagl_transport_get_out_yagl_host_handle(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glEGLImageTargetTexture2DOES, GLenum, yagl_host_handle, target, image);
    (void)yagl_host_glEGLImageTargetTexture2DOES(target, image);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glEnable dispatcher. id = 33
 */
static bool yagl_func_glEnable(struct yagl_transport *t)
{
    GLenum cap;
    cap = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glEnable, GLenum, cap);
    (void)yagl_host_glEnable(cap);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glFlush dispatcher. id = 34
 */
static bool yagl_func_glFlush(struct yagl_transport *t)
{
    YAGL_LOG_FUNC_ENTER_SPLIT0(glFlush);
    (void)yagl_host_glFlush();
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glFramebufferTexture2D dispatcher. id = 35
 */
static bool yagl_func_glFramebufferTexture2D(struct yagl_transport *t)
{
    GLenum target;
    GLenum attachment;
    GLenum textarget;
    GLuint texture;
    GLint level;
    target = yagl_transport_get_out_GLenum(t);
    attachment = yagl_transport_get_out_GLenum(t);
    textarget = yagl_transport_get_out_GLenum(t);
    texture = yagl_transport_get_out_GLuint(t);
    level = yagl_transport_get_out_GLint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glFramebufferTexture2D, GLenum, GLenum, GLenum, GLuint, GLint, target, attachment, textarget, texture, level);
    (void)yagl_host_glFramebufferTexture2D(target, attachment, textarget, texture, level);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glFramebufferRenderbuffer dispatcher. id = 36
 */
static bool yagl_func_glFramebufferRenderbuffer(struct yagl_transport *t)
{
    GLenum target;
    GLenum attachment;
    GLenum renderbuffertarget;
    GLuint renderbuffer;
    target = yagl_transport_get_out_GLenum(t);
    attachment = yagl_transport_get_out_GLenum(t);
    renderbuffertarget = yagl_transport_get_out_GLenum(t);
    renderbuffer = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glFramebufferRenderbuffer, GLenum, GLenum, GLenum, GLuint, target, attachment, renderbuffertarget, renderbuffer);
    (void)yagl_host_glFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glFrontFace dispatcher. id = 37
 */
static bool yagl_func_glFrontFace(struct yagl_transport *t)
{
    GLenum mode;
    mode = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glFrontFace, GLenum, mode);
    (void)yagl_host_glFrontFace(mode);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGenBuffers dispatcher. id = 38
 */
static bool yagl_func_glGenBuffers(struct yagl_transport *t)
{
    GLuint *buffers;
    int32_t buffers_maxcount;
    int32_t *buffers_count;
    if (!yagl_transport_get_in_array(t, sizeof(GLuint), (void**)&buffers, &buffers_maxcount, &buffers_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT1(glGenBuffers, void*, buffers);
    *buffers_count = 0;
    (void)yagl_host_glGenBuffers(buffers, buffers_maxcount, buffers_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGenerateMipmap dispatcher. id = 39
 */
static bool yagl_func_glGenerateMipmap(struct yagl_transport *t)
{
    GLenum target;
    target = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glGenerateMipmap, GLenum, target);
    (void)yagl_host_glGenerateMipmap(target);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGenFramebuffers dispatcher. id = 40
 */
static bool yagl_func_glGenFramebuffers(struct yagl_transport *t)
{
    GLuint *framebuffers;
    int32_t framebuffers_maxcount;
    int32_t *framebuffers_count;
    if (!yagl_transport_get_in_array(t, sizeof(GLuint), (void**)&framebuffers, &framebuffers_maxcount, &framebuffers_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT1(glGenFramebuffers, void*, framebuffers);
    *framebuffers_count = 0;
    (void)yagl_host_glGenFramebuffers(framebuffers, framebuffers_maxcount, framebuffers_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGenRenderbuffers dispatcher. id = 41
 */
static bool yagl_func_glGenRenderbuffers(struct yagl_transport *t)
{
    GLuint *renderbuffers;
    int32_t renderbuffers_maxcount;
    int32_t *renderbuffers_count;
    if (!yagl_transport_get_in_array(t, sizeof(GLuint), (void**)&renderbuffers, &renderbuffers_maxcount, &renderbuffers_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT1(glGenRenderbuffers, void*, renderbuffers);
    *renderbuffers_count = 0;
    (void)yagl_host_glGenRenderbuffers(renderbuffers, renderbuffers_maxcount, renderbuffers_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGenTextures dispatcher. id = 42
 */
static bool yagl_func_glGenTextures(struct yagl_transport *t)
{
    GLuint *textures;
    int32_t textures_maxcount;
    int32_t *textures_count;
    if (!yagl_transport_get_in_array(t, sizeof(GLuint), (void**)&textures, &textures_maxcount, &textures_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT1(glGenTextures, void*, textures);
    *textures_count = 0;
    (void)yagl_host_glGenTextures(textures, textures_maxcount, textures_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetBooleanv dispatcher. id = 43
 */
static bool yagl_func_glGetBooleanv(struct yagl_transport *t)
{
    GLenum pname;
    GLboolean *params;
    int32_t params_maxcount;
    int32_t *params_count;
    pname = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLboolean), (void**)&params, &params_maxcount, &params_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetBooleanv, GLenum, void*, pname, params);
    *params_count = 0;
    (void)yagl_host_glGetBooleanv(pname, params, params_maxcount, params_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetBufferParameteriv dispatcher. id = 44
 */
static bool yagl_func_glGetBufferParameteriv(struct yagl_transport *t)
{
    GLenum target;
    GLenum pname;
    GLint *param;
    target = yagl_transport_get_out_GLenum(t);
    pname = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&param);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetBufferParameteriv, GLenum, GLenum, void*, target, pname, param);
    (void)yagl_host_glGetBufferParameteriv(target, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetError dispatcher. id = 45
 */
static bool yagl_func_glGetError(struct yagl_transport *t)
{
    GLenum *retval;
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT0(glGetError);
    *retval = yagl_host_glGetError();
    YAGL_LOG_FUNC_EXIT_SPLIT(GLenum, *retval);

    return true;
}

/*
 * glGetFloatv dispatcher. id = 46
 */
static bool yagl_func_glGetFloatv(struct yagl_transport *t)
{
    GLenum pname;
    GLfloat *params;
    int32_t params_maxcount;
    int32_t *params_count;
    pname = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLfloat), (void**)&params, &params_maxcount, &params_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetFloatv, GLenum, void*, pname, params);
    *params_count = 0;
    (void)yagl_host_glGetFloatv(pname, params, params_maxcount, params_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetFramebufferAttachmentParameteriv dispatcher. id = 47
 */
static bool yagl_func_glGetFramebufferAttachmentParameteriv(struct yagl_transport *t)
{
    GLenum target;
    GLenum attachment;
    GLenum pname;
    GLint *param;
    target = yagl_transport_get_out_GLenum(t);
    attachment = yagl_transport_get_out_GLenum(t);
    pname = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&param);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glGetFramebufferAttachmentParameteriv, GLenum, GLenum, GLenum, void*, target, attachment, pname, param);
    (void)yagl_host_glGetFramebufferAttachmentParameteriv(target, attachment, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetIntegerv dispatcher. id = 48
 */
static bool yagl_func_glGetIntegerv(struct yagl_transport *t)
{
    GLenum pname;
    GLint *params;
    int32_t params_maxcount;
    int32_t *params_count;
    pname = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLint), (void**)&params, &params_maxcount, &params_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetIntegerv, GLenum, void*, pname, params);
    *params_count = 0;
    (void)yagl_host_glGetIntegerv(pname, params, params_maxcount, params_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetRenderbufferParameteriv dispatcher. id = 49
 */
static bool yagl_func_glGetRenderbufferParameteriv(struct yagl_transport *t)
{
    GLenum target;
    GLenum pname;
    GLint *param;
    target = yagl_transport_get_out_GLenum(t);
    pname = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&param);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetRenderbufferParameteriv, GLenum, GLenum, void*, target, pname, param);
    (void)yagl_host_glGetRenderbufferParameteriv(target, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetTexParameterfv dispatcher. id = 50
 */
static bool yagl_func_glGetTexParameterfv(struct yagl_transport *t)
{
    GLenum target;
    GLenum pname;
    GLfloat *param;
    target = yagl_transport_get_out_GLenum(t);
    pname = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&param);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetTexParameterfv, GLenum, GLenum, void*, target, pname, param);
    (void)yagl_host_glGetTexParameterfv(target, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetTexParameteriv dispatcher. id = 51
 */
static bool yagl_func_glGetTexParameteriv(struct yagl_transport *t)
{
    GLenum target;
    GLenum pname;
    GLint *param;
    target = yagl_transport_get_out_GLenum(t);
    pname = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&param);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetTexParameteriv, GLenum, GLenum, void*, target, pname, param);
    (void)yagl_host_glGetTexParameteriv(target, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glHint dispatcher. id = 52
 */
static bool yagl_func_glHint(struct yagl_transport *t)
{
    GLenum target;
    GLenum mode;
    target = yagl_transport_get_out_GLenum(t);
    mode = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glHint, GLenum, GLenum, target, mode);
    (void)yagl_host_glHint(target, mode);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glIsBuffer dispatcher. id = 53
 */
static bool yagl_func_glIsBuffer(struct yagl_transport *t)
{
    GLuint buffer;
    GLboolean *retval;
    buffer = yagl_transport_get_out_GLuint(t);
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsBuffer, GLuint, buffer);
    *retval = yagl_host_glIsBuffer(buffer);
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, *retval);

    return true;
}

/*
 * glIsEnabled dispatcher. id = 54
 */
static bool yagl_func_glIsEnabled(struct yagl_transport *t)
{
    GLenum cap;
    GLboolean *retval;
    cap = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsEnabled, GLenum, cap);
    *retval = yagl_host_glIsEnabled(cap);
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, *retval);

    return true;
}

/*
 * glIsFramebuffer dispatcher. id = 55
 */
static bool yagl_func_glIsFramebuffer(struct yagl_transport *t)
{
    GLuint framebuffer;
    GLboolean *retval;
    framebuffer = yagl_transport_get_out_GLuint(t);
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsFramebuffer, GLuint, framebuffer);
    *retval = yagl_host_glIsFramebuffer(framebuffer);
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, *retval);

    return true;
}

/*
 * glIsRenderbuffer dispatcher. id = 56
 */
static bool yagl_func_glIsRenderbuffer(struct yagl_transport *t)
{
    GLuint renderbuffer;
    GLboolean *retval;
    renderbuffer = yagl_transport_get_out_GLuint(t);
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsRenderbuffer, GLuint, renderbuffer);
    *retval = yagl_host_glIsRenderbuffer(renderbuffer);
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, *retval);

    return true;
}

/*
 * glIsTexture dispatcher. id = 57
 */
static bool yagl_func_glIsTexture(struct yagl_transport *t)
{
    GLuint texture;
    GLboolean *retval;
    texture = yagl_transport_get_out_GLuint(t);
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsTexture, GLuint, texture);
    *retval = yagl_host_glIsTexture(texture);
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, *retval);

    return true;
}

/*
 * glLineWidth dispatcher. id = 58
 */
static bool yagl_func_glLineWidth(struct yagl_transport *t)
{
    GLfloat width;
    width = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glLineWidth, GLfloat, width);
    (void)yagl_host_glLineWidth(width);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glPixelStorei dispatcher. id = 59
 */
static bool yagl_func_glPixelStorei(struct yagl_transport *t)
{
    GLenum pname;
    GLint param;
    pname = yagl_transport_get_out_GLenum(t);
    param = yagl_transport_get_out_GLint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glPixelStorei, GLenum, GLint, pname, param);
    (void)yagl_host_glPixelStorei(pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glPolygonOffset dispatcher. id = 60
 */
static bool yagl_func_glPolygonOffset(struct yagl_transport *t)
{
    GLfloat factor;
    GLfloat units;
    factor = yagl_transport_get_out_GLfloat(t);
    units = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glPolygonOffset, GLfloat, GLfloat, factor, units);
    (void)yagl_host_glPolygonOffset(factor, units);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glReadPixels dispatcher. id = 61
 */
static bool yagl_func_glReadPixels(struct yagl_transport *t)
{
    GLint x;
    GLint y;
    GLsizei width;
    GLsizei height;
    GLenum format;
    GLenum type;
    GLvoid *pixels;
    int32_t pixels_maxcount;
    int32_t *pixels_count;
    x = yagl_transport_get_out_GLint(t);
    y = yagl_transport_get_out_GLint(t);
    width = yagl_transport_get_out_GLsizei(t);
    height = yagl_transport_get_out_GLsizei(t);
    format = yagl_transport_get_out_GLenum(t);
    type = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_in_array(t, 1, (void**)&pixels, &pixels_maxcount, &pixels_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT7(glReadPixels, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, void*, x, y, width, height, format, type, pixels);
    *pixels_count = 0;
    (void)yagl_host_glReadPixels(x, y, width, height, format, type, pixels, pixels_maxcount, pixels_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glRenderbufferStorage dispatcher. id = 62
 */
static bool yagl_func_glRenderbufferStorage(struct yagl_transport *t)
{
    GLenum target;
    GLenum internalformat;
    GLsizei width;
    GLsizei height;
    target = yagl_transport_get_out_GLenum(t);
    internalformat = yagl_transport_get_out_GLenum(t);
    width = yagl_transport_get_out_GLsizei(t);
    height = yagl_transport_get_out_GLsizei(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glRenderbufferStorage, GLenum, GLenum, GLsizei, GLsizei, target, internalformat, width, height);
    (void)yagl_host_glRenderbufferStorage(target, internalformat, width, height);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glSampleCoverage dispatcher. id = 63
 */
static bool yagl_func_glSampleCoverage(struct yagl_transport *t)
{
    GLclampf value;
    GLboolean invert;
    value = yagl_transport_get_out_GLclampf(t);
    invert = yagl_transport_get_out_GLboolean(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glSampleCoverage, GLclampf, GLboolean, value, invert);
    (void)yagl_host_glSampleCoverage(value, invert);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glScissor dispatcher. id = 64
 */
static bool yagl_func_glScissor(struct yagl_transport *t)
{
    GLint x;
    GLint y;
    GLsizei width;
    GLsizei height;
    x = yagl_transport_get_out_GLint(t);
    y = yagl_transport_get_out_GLint(t);
    width = yagl_transport_get_out_GLsizei(t);
    height = yagl_transport_get_out_GLsizei(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glScissor, GLint, GLint, GLsizei, GLsizei, x, y, width, height);
    (void)yagl_host_glScissor(x, y, width, height);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glStencilFunc dispatcher. id = 65
 */
static bool yagl_func_glStencilFunc(struct yagl_transport *t)
{
    GLenum func;
    GLint ref;
    GLuint mask;
    func = yagl_transport_get_out_GLenum(t);
    ref = yagl_transport_get_out_GLint(t);
    mask = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glStencilFunc, GLenum, GLint, GLuint, func, ref, mask);
    (void)yagl_host_glStencilFunc(func, ref, mask);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glStencilMask dispatcher. id = 66
 */
static bool yagl_func_glStencilMask(struct yagl_transport *t)
{
    GLuint mask;
    mask = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glStencilMask, GLuint, mask);
    (void)yagl_host_glStencilMask(mask);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glStencilOp dispatcher. id = 67
 */
static bool yagl_func_glStencilOp(struct yagl_transport *t)
{
    GLenum fail;
    GLenum zfail;
    GLenum zpass;
    fail = yagl_transport_get_out_GLenum(t);
    zfail = yagl_transport_get_out_GLenum(t);
    zpass = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glStencilOp, GLenum, GLenum, GLenum, fail, zfail, zpass);
    (void)yagl_host_glStencilOp(fail, zfail, zpass);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glTexImage2D dispatcher. id = 68
 */
static bool yagl_func_glTexImage2D(struct yagl_transport *t)
{
    GLenum target;
    GLint level;
    GLint internalformat;
    GLsizei width;
    GLsizei height;
    GLint border;
    GLenum format;
    GLenum type;
    const GLvoid *pixels;
    int32_t pixels_count;
    target = yagl_transport_get_out_GLenum(t);
    level = yagl_transport_get_out_GLint(t);
    internalformat = yagl_transport_get_out_GLint(t);
    width = yagl_transport_get_out_GLsizei(t);
    height = yagl_transport_get_out_GLsizei(t);
    border = yagl_transport_get_out_GLint(t);
    format = yagl_transport_get_out_GLenum(t);
    type = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_out_array(t, 1, (const void**)&pixels, &pixels_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT9(glTexImage2D, GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, void*, target, level, internalformat, width, height, border, format, type, pixels);
    (void)yagl_host_glTexImage2D(target, level, internalformat, width, height, border, format, type, pixels, pixels_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glTexParameterf dispatcher. id = 69
 */
static bool yagl_func_glTexParameterf(struct yagl_transport *t)
{
    GLenum target;
    GLenum pname;
    GLfloat param;
    target = yagl_transport_get_out_GLenum(t);
    pname = yagl_transport_get_out_GLenum(t);
    param = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glTexParameterf, GLenum, GLenum, GLfloat, target, pname, param);
    (void)yagl_host_glTexParameterf(target, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glTexParameterfv dispatcher. id = 70
 */
static bool yagl_func_glTexParameterfv(struct yagl_transport *t)
{
    GLenum target;
    GLenum pname;
    const GLfloat *params;
    int32_t params_count;
    target = yagl_transport_get_out_GLenum(t);
    pname = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&params, &params_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glTexParameterfv, GLenum, GLenum, void*, target, pname, params);
    (void)yagl_host_glTexParameterfv(target, pname, params, params_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glTexParameteri dispatcher. id = 71
 */
static bool yagl_func_glTexParameteri(struct yagl_transport *t)
{
    GLenum target;
    GLenum pname;
    GLint param;
    target = yagl_transport_get_out_GLenum(t);
    pname = yagl_transport_get_out_GLenum(t);
    param = yagl_transport_get_out_GLint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glTexParameteri, GLenum, GLenum, GLint, target, pname, param);
    (void)yagl_host_glTexParameteri(target, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glTexParameteriv dispatcher. id = 72
 */
static bool yagl_func_glTexParameteriv(struct yagl_transport *t)
{
    GLenum target;
    GLenum pname;
    const GLint *params;
    int32_t params_count;
    target = yagl_transport_get_out_GLenum(t);
    pname = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLint), (const void**)&params, &params_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glTexParameteriv, GLenum, GLenum, void*, target, pname, params);
    (void)yagl_host_glTexParameteriv(target, pname, params, params_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glTexSubImage2D dispatcher. id = 73
 */
static bool yagl_func_glTexSubImage2D(struct yagl_transport *t)
{
    GLenum target;
    GLint level;
    GLint xoffset;
    GLint yoffset;
    GLsizei width;
    GLsizei height;
    GLenum format;
    GLenum type;
    const GLvoid *pixels;
    int32_t pixels_count;
    target = yagl_transport_get_out_GLenum(t);
    level = yagl_transport_get_out_GLint(t);
    xoffset = yagl_transport_get_out_GLint(t);
    yoffset = yagl_transport_get_out_GLint(t);
    width = yagl_transport_get_out_GLsizei(t);
    height = yagl_transport_get_out_GLsizei(t);
    format = yagl_transport_get_out_GLenum(t);
    type = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_out_array(t, 1, (const void**)&pixels, &pixels_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT9(glTexSubImage2D, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, void*, target, level, xoffset, yoffset, width, height, format, type, pixels);
    (void)yagl_host_glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels, pixels_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glViewport dispatcher. id = 74
 */
static bool yagl_func_glViewport(struct yagl_transport *t)
{
    GLint x;
    GLint y;
    GLsizei width;
    GLsizei height;
    x = yagl_transport_get_out_GLint(t);
    y = yagl_transport_get_out_GLint(t);
    width = yagl_transport_get_out_GLsizei(t);
    height = yagl_transport_get_out_GLsizei(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glViewport, GLint, GLint, GLsizei, GLsizei, x, y, width, height);
    (void)yagl_host_glViewport(x, y, width, height);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glTransferArrayYAGL dispatcher. id = 75
 */
static bool yagl_func_glTransferArrayYAGL(struct yagl_transport *t)
{
    GLuint indx;
    GLint first;
    const GLvoid *data;
    int32_t data_count;
    indx = yagl_transport_get_out_GLuint(t);
    first = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_out_array(t, 1, (const void**)&data, &data_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glTransferArrayYAGL, GLuint, GLint, void*, indx, first, data);
    (void)yagl_host_glTransferArrayYAGL(indx, first, data, data_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDrawElementsIndicesYAGL dispatcher. id = 76
 */
static bool yagl_func_glDrawElementsIndicesYAGL(struct yagl_transport *t)
{
    GLenum mode;
    GLenum type;
    const GLvoid *indices;
    int32_t indices_count;
    mode = yagl_transport_get_out_GLenum(t);
    type = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_out_array(t, 1, (const void**)&indices, &indices_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glDrawElementsIndicesYAGL, GLenum, GLenum, void*, mode, type, indices);
    (void)yagl_host_glDrawElementsIndicesYAGL(mode, type, indices, indices_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDrawElementsOffsetYAGL dispatcher. id = 77
 */
static bool yagl_func_glDrawElementsOffsetYAGL(struct yagl_transport *t)
{
    GLenum mode;
    GLenum type;
    GLsizei offset;
    GLsizei count;
    mode = yagl_transport_get_out_GLenum(t);
    type = yagl_transport_get_out_GLenum(t);
    offset = yagl_transport_get_out_GLsizei(t);
    count = yagl_transport_get_out_GLsizei(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glDrawElementsOffsetYAGL, GLenum, GLenum, GLsizei, GLsizei, mode, type, offset, count);
    (void)yagl_host_glDrawElementsOffsetYAGL(mode, type, offset, count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetExtensionStringYAGL dispatcher. id = 78
 */
static bool yagl_func_glGetExtensionStringYAGL(struct yagl_transport *t)
{
    GLchar *str;
    int32_t str_maxcount;
    int32_t *str_count;
    if (!yagl_transport_get_in_array(t, sizeof(GLchar), (void**)&str, &str_maxcount, &str_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT1(glGetExtensionStringYAGL, void*, str);
    *str_count = 0;
    (void)yagl_host_glGetExtensionStringYAGL(str, str_maxcount, str_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetVertexAttribRangeYAGL dispatcher. id = 79
 */
static bool yagl_func_glGetVertexAttribRangeYAGL(struct yagl_transport *t)
{
    GLenum type;
    GLsizei offset;
    GLsizei count;
    GLint *range_first;
    GLsizei *range_count;
    type = yagl_transport_get_out_GLenum(t);
    offset = yagl_transport_get_out_GLsizei(t);
    count = yagl_transport_get_out_GLsizei(t);
    yagl_transport_get_in_arg(t, (void**)&range_first);
    yagl_transport_get_in_arg(t, (void**)&range_count);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glGetVertexAttribRangeYAGL, GLenum, GLsizei, GLsizei, void*, void*, type, offset, count, range_first, range_count);
    (void)yagl_host_glGetVertexAttribRangeYAGL(type, offset, count, range_first, range_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glAttachShader dispatcher. id = 80
 */
static bool yagl_func_glAttachShader(struct yagl_transport *t)
{
    GLuint program;
    GLuint shader;
    program = yagl_transport_get_out_GLuint(t);
    shader = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glAttachShader, GLuint, GLuint, program, shader);
    (void)yagl_host_glAttachShader(program, shader);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBindAttribLocation dispatcher. id = 81
 */
static bool yagl_func_glBindAttribLocation(struct yagl_transport *t)
{
    GLuint program;
    GLuint index;
    const GLchar *name;
    int32_t name_count;
    program = yagl_transport_get_out_GLuint(t);
    index = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLchar), (const void**)&name, &name_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glBindAttribLocation, GLuint, GLuint, void*, program, index, name);
    (void)yagl_host_glBindAttribLocation(program, index, name, name_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glBlendColor dispatcher. id = 82
 */
static bool yagl_func_glBlendColor(struct yagl_transport *t)
{
    GLclampf red;
    GLclampf green;
    GLclampf blue;
    GLclampf alpha;
    red = yagl_transport_get_out_GLclampf(t);
    green = yagl_transport_get_out_GLclampf(t);
    blue = yagl_transport_get_out_GLclampf(t);
    alpha = yagl_transport_get_out_GLclampf(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glBlendColor, GLclampf, GLclampf, GLclampf, GLclampf, red, green, blue, alpha);
    (void)yagl_host_glBlendColor(red, green, blue, alpha);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glCompileShader dispatcher. id = 83
 */
static bool yagl_func_glCompileShader(struct yagl_transport *t)
{
    GLuint shader;
    shader = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glCompileShader, GLuint, shader);
    (void)yagl_host_glCompileShader(shader);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glCreateProgram dispatcher. id = 84
 */
static bool yagl_func_glCreateProgram(struct yagl_transport *t)
{
    GLuint *retval;
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT0(glCreateProgram);
    *retval = yagl_host_glCreateProgram();
    YAGL_LOG_FUNC_EXIT_SPLIT(GLuint, *retval);

    return true;
}

/*
 * glCreateShader dispatcher. id = 85
 */
static bool yagl_func_glCreateShader(struct yagl_transport *t)
{
    GLenum type;
    GLuint *retval;
    type = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glCreateShader, GLenum, type);
    *retval = yagl_host_glCreateShader(type);
    YAGL_LOG_FUNC_EXIT_SPLIT(GLuint, *retval);

    return true;
}

/*
 * glDeleteProgram dispatcher. id = 86
 */
static bool yagl_func_glDeleteProgram(struct yagl_transport *t)
{
    GLuint program;
    program = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDeleteProgram, GLuint, program);
    (void)yagl_host_glDeleteProgram(program);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDeleteShader dispatcher. id = 87
 */
static bool yagl_func_glDeleteShader(struct yagl_transport *t)
{
    GLuint shader;
    shader = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDeleteShader, GLuint, shader);
    (void)yagl_host_glDeleteShader(shader);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDetachShader dispatcher. id = 88
 */
static bool yagl_func_glDetachShader(struct yagl_transport *t)
{
    GLuint program;
    GLuint shader;
    program = yagl_transport_get_out_GLuint(t);
    shader = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glDetachShader, GLuint, GLuint, program, shader);
    (void)yagl_host_glDetachShader(program, shader);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glDisableVertexAttribArray dispatcher. id = 89
 */
static bool yagl_func_glDisableVertexAttribArray(struct yagl_transport *t)
{
    GLuint index;
    index = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDisableVertexAttribArray, GLuint, index);
    (void)yagl_host_glDisableVertexAttribArray(index);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glEnableVertexAttribArray dispatcher. id = 90
 */
static bool yagl_func_glEnableVertexAttribArray(struct yagl_transport *t)
{
    GLuint index;
    index = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glEnableVertexAttribArray, GLuint, index);
    (void)yagl_host_glEnableVertexAttribArray(index);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetActiveAttrib dispatcher. id = 91
 */
static bool yagl_func_glGetActiveAttrib(struct yagl_transport *t)
{
    GLuint program;
    GLuint index;
    GLint *size;
    GLenum *type;
    GLchar *name;
    int32_t name_maxcount;
    int32_t *name_count;
    program = yagl_transport_get_out_GLuint(t);
    index = yagl_transport_get_out_GLuint(t);
    yagl_transport_get_in_arg(t, (void**)&size);
    yagl_transport_get_in_arg(t, (void**)&type);
    if (!yagl_transport_get_in_array(t, sizeof(GLchar), (void**)&name, &name_maxcount, &name_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT5(glGetActiveAttrib, GLuint, GLuint, void*, void*, void*, program, index, size, type, name);
    *name_count = 0;
    (void)yagl_host_glGetActiveAttrib(program, index, size, type, name, name_maxcount, name_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetActiveUniform dispatcher. id = 92
 */
static bool yagl_func_glGetActiveUniform(struct yagl_transport *t)
{
    GLuint program;
    GLuint index;
    GLint *size;
    GLenum *type;
    GLchar *name;
    int32_t name_maxcount;
    int32_t *name_count;
    program = yagl_transport_get_out_GLuint(t);
    index = yagl_transport_get_out_GLuint(t);
    yagl_transport_get_in_arg(t, (void**)&size);
    yagl_transport_get_in_arg(t, (void**)&type);
    if (!yagl_transport_get_in_array(t, sizeof(GLchar), (void**)&name, &name_maxcount, &name_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT5(glGetActiveUniform, GLuint, GLuint, void*, void*, void*, program, index, size, type, name);
    *name_count = 0;
    (void)yagl_host_glGetActiveUniform(program, index, size, type, name, name_maxcount, name_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetAttachedShaders dispatcher. id = 93
 */
static bool yagl_func_glGetAttachedShaders(struct yagl_transport *t)
{
    GLuint program;
    GLuint *shaders;
    int32_t shaders_maxcount;
    int32_t *shaders_count;
    program = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLuint), (void**)&shaders, &shaders_maxcount, &shaders_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetAttachedShaders, GLuint, void*, program, shaders);
    *shaders_count = 0;
    (void)yagl_host_glGetAttachedShaders(program, shaders, shaders_maxcount, shaders_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetAttribLocation dispatcher. id = 94
 */
static bool yagl_func_glGetAttribLocation(struct yagl_transport *t)
{
    GLuint program;
    const GLchar *name;
    int32_t name_count;
    int *retval;
    program = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLchar), (const void**)&name, &name_count)) {
        return false;
    }
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetAttribLocation, GLuint, void*, program, name);
    *retval = yagl_host_glGetAttribLocation(program, name, name_count);
    YAGL_LOG_FUNC_EXIT_SPLIT(int, *retval);

    return true;
}

/*
 * glGetProgramiv dispatcher. id = 95
 */
static bool yagl_func_glGetProgramiv(struct yagl_transport *t)
{
    GLuint program;
    GLenum pname;
    GLint *param;
    program = yagl_transport_get_out_GLuint(t);
    pname = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&param);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetProgramiv, GLuint, GLenum, void*, program, pname, param);
    (void)yagl_host_glGetProgramiv(program, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetProgramInfoLog dispatcher. id = 96
 */
static bool yagl_func_glGetProgramInfoLog(struct yagl_transport *t)
{
    GLuint program;
    GLchar *infolog;
    int32_t infolog_maxcount;
    int32_t *infolog_count;
    program = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLchar), (void**)&infolog, &infolog_maxcount, &infolog_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetProgramInfoLog, GLuint, void*, program, infolog);
    *infolog_count = 0;
    (void)yagl_host_glGetProgramInfoLog(program, infolog, infolog_maxcount, infolog_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetShaderiv dispatcher. id = 97
 */
static bool yagl_func_glGetShaderiv(struct yagl_transport *t)
{
    GLuint shader;
    GLenum pname;
    GLint *param;
    shader = yagl_transport_get_out_GLuint(t);
    pname = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&param);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetShaderiv, GLuint, GLenum, void*, shader, pname, param);
    (void)yagl_host_glGetShaderiv(shader, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetShaderInfoLog dispatcher. id = 98
 */
static bool yagl_func_glGetShaderInfoLog(struct yagl_transport *t)
{
    GLuint shader;
    GLchar *infolog;
    int32_t infolog_maxcount;
    int32_t *infolog_count;
    shader = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLchar), (void**)&infolog, &infolog_maxcount, &infolog_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetShaderInfoLog, GLuint, void*, shader, infolog);
    *infolog_count = 0;
    (void)yagl_host_glGetShaderInfoLog(shader, infolog, infolog_maxcount, infolog_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetShaderPrecisionFormat dispatcher. id = 99
 */
static bool yagl_func_glGetShaderPrecisionFormat(struct yagl_transport *t)
{
    GLenum shadertype;
    GLenum precisiontype;
    GLint *range;
    int32_t range_maxcount;
    int32_t *range_count;
    GLint *precision;
    shadertype = yagl_transport_get_out_GLenum(t);
    precisiontype = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLint), (void**)&range, &range_maxcount, &range_count)) {
        return false;
    }
    yagl_transport_get_in_arg(t, (void**)&precision);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glGetShaderPrecisionFormat, GLenum, GLenum, void*, void*, shadertype, precisiontype, range, precision);
    *range_count = 0;
    (void)yagl_host_glGetShaderPrecisionFormat(shadertype, precisiontype, range, range_maxcount, range_count, precision);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetShaderSource dispatcher. id = 100
 */
static bool yagl_func_glGetShaderSource(struct yagl_transport *t)
{
    GLuint shader;
    GLchar *source;
    int32_t source_maxcount;
    int32_t *source_count;
    shader = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLchar), (void**)&source, &source_maxcount, &source_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetShaderSource, GLuint, void*, shader, source);
    *source_count = 0;
    (void)yagl_host_glGetShaderSource(shader, source, source_maxcount, source_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetUniformfv dispatcher. id = 101
 */
static bool yagl_func_glGetUniformfv(struct yagl_transport *t)
{
    GLuint program;
    GLint location;
    GLfloat *params;
    int32_t params_maxcount;
    int32_t *params_count;
    program = yagl_transport_get_out_GLuint(t);
    location = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLfloat), (void**)&params, &params_maxcount, &params_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetUniformfv, GLuint, GLint, void*, program, location, params);
    *params_count = 0;
    (void)yagl_host_glGetUniformfv(program, location, params, params_maxcount, params_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetUniformiv dispatcher. id = 102
 */
static bool yagl_func_glGetUniformiv(struct yagl_transport *t)
{
    GLuint program;
    GLint location;
    GLint *params;
    int32_t params_maxcount;
    int32_t *params_count;
    program = yagl_transport_get_out_GLuint(t);
    location = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLint), (void**)&params, &params_maxcount, &params_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetUniformiv, GLuint, GLint, void*, program, location, params);
    *params_count = 0;
    (void)yagl_host_glGetUniformiv(program, location, params, params_maxcount, params_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetUniformLocation dispatcher. id = 103
 */
static bool yagl_func_glGetUniformLocation(struct yagl_transport *t)
{
    GLuint program;
    const GLchar *name;
    int32_t name_count;
    int *retval;
    program = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLchar), (const void**)&name, &name_count)) {
        return false;
    }
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetUniformLocation, GLuint, void*, program, name);
    *retval = yagl_host_glGetUniformLocation(program, name, name_count);
    YAGL_LOG_FUNC_EXIT_SPLIT(int, *retval);

    return true;
}

/*
 * glGetVertexAttribfv dispatcher. id = 104
 */
static bool yagl_func_glGetVertexAttribfv(struct yagl_transport *t)
{
    GLuint index;
    GLenum pname;
    GLfloat *params;
    int32_t params_maxcount;
    int32_t *params_count;
    index = yagl_transport_get_out_GLuint(t);
    pname = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLfloat), (void**)&params, &params_maxcount, &params_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetVertexAttribfv, GLuint, GLenum, void*, index, pname, params);
    *params_count = 0;
    (void)yagl_host_glGetVertexAttribfv(index, pname, params, params_maxcount, params_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetVertexAttribiv dispatcher. id = 105
 */
static bool yagl_func_glGetVertexAttribiv(struct yagl_transport *t)
{
    GLuint index;
    GLenum pname;
    GLint *params;
    int32_t params_maxcount;
    int32_t *params_count;
    index = yagl_transport_get_out_GLuint(t);
    pname = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_in_array(t, sizeof(GLint), (void**)&params, &params_maxcount, &params_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetVertexAttribiv, GLuint, GLenum, void*, index, pname, params);
    *params_count = 0;
    (void)yagl_host_glGetVertexAttribiv(index, pname, params, params_maxcount, params_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glGetVertexAttribPointerv dispatcher. id = 106
 */
static bool yagl_func_glGetVertexAttribPointerv(struct yagl_transport *t)
{
    GLuint index;
    GLenum pname;
    target_ulong *pointer;
    index = yagl_transport_get_out_GLuint(t);
    pname = yagl_transport_get_out_GLenum(t);
    yagl_transport_get_in_arg(t, (void**)&pointer);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetVertexAttribPointerv, GLuint, GLenum, target_ulong*, index, pname, pointer);
    (void)yagl_host_glGetVertexAttribPointerv(index, pname, pointer);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glIsProgram dispatcher. id = 107
 */
static bool yagl_func_glIsProgram(struct yagl_transport *t)
{
    GLuint program;
    GLboolean *retval;
    program = yagl_transport_get_out_GLuint(t);
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsProgram, GLuint, program);
    *retval = yagl_host_glIsProgram(program);
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, *retval);

    return true;
}

/*
 * glIsShader dispatcher. id = 108
 */
static bool yagl_func_glIsShader(struct yagl_transport *t)
{
    GLuint shader;
    GLboolean *retval;
    shader = yagl_transport_get_out_GLuint(t);
    yagl_transport_get_in_arg(t, (void**)&retval);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsShader, GLuint, shader);
    *retval = yagl_host_glIsShader(shader);
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, *retval);

    return true;
}

/*
 * glLinkProgram dispatcher. id = 109
 */
static bool yagl_func_glLinkProgram(struct yagl_transport *t)
{
    GLuint program;
    program = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glLinkProgram, GLuint, program);
    (void)yagl_host_glLinkProgram(program);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glReleaseShaderCompiler dispatcher. id = 110
 */
static bool yagl_func_glReleaseShaderCompiler(struct yagl_transport *t)
{
    YAGL_LOG_FUNC_ENTER_SPLIT0(glReleaseShaderCompiler);
    (void)yagl_host_glReleaseShaderCompiler();
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glShaderBinary dispatcher. id = 111
 */
static bool yagl_func_glShaderBinary(struct yagl_transport *t)
{
    const GLuint *shaders;
    int32_t shaders_count;
    GLenum binaryformat;
    const GLvoid *binary;
    int32_t binary_count;
    if (!yagl_transport_get_out_array(t, sizeof(GLuint), (const void**)&shaders, &shaders_count)) {
        return false;
    }
    binaryformat = yagl_transport_get_out_GLenum(t);
    if (!yagl_transport_get_out_array(t, 1, (const void**)&binary, &binary_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glShaderBinary, void*, GLenum, void*, shaders, binaryformat, binary);
    (void)yagl_host_glShaderBinary(shaders, shaders_count, binaryformat, binary, binary_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glShaderSource dispatcher. id = 112
 */
static bool yagl_func_glShaderSource(struct yagl_transport *t)
{
    GLuint shader;
    const GLchar *string;
    int32_t string_count;
    shader = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLchar), (const void**)&string, &string_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glShaderSource, GLuint, void*, shader, string);
    (void)yagl_host_glShaderSource(shader, string, string_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glStencilFuncSeparate dispatcher. id = 113
 */
static bool yagl_func_glStencilFuncSeparate(struct yagl_transport *t)
{
    GLenum face;
    GLenum func;
    GLint ref;
    GLuint mask;
    face = yagl_transport_get_out_GLenum(t);
    func = yagl_transport_get_out_GLenum(t);
    ref = yagl_transport_get_out_GLint(t);
    mask = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glStencilFuncSeparate, GLenum, GLenum, GLint, GLuint, face, func, ref, mask);
    (void)yagl_host_glStencilFuncSeparate(face, func, ref, mask);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glStencilMaskSeparate dispatcher. id = 114
 */
static bool yagl_func_glStencilMaskSeparate(struct yagl_transport *t)
{
    GLenum face;
    GLuint mask;
    face = yagl_transport_get_out_GLenum(t);
    mask = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glStencilMaskSeparate, GLenum, GLuint, face, mask);
    (void)yagl_host_glStencilMaskSeparate(face, mask);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glStencilOpSeparate dispatcher. id = 115
 */
static bool yagl_func_glStencilOpSeparate(struct yagl_transport *t)
{
    GLenum face;
    GLenum fail;
    GLenum zfail;
    GLenum zpass;
    face = yagl_transport_get_out_GLenum(t);
    fail = yagl_transport_get_out_GLenum(t);
    zfail = yagl_transport_get_out_GLenum(t);
    zpass = yagl_transport_get_out_GLenum(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glStencilOpSeparate, GLenum, GLenum, GLenum, GLenum, face, fail, zfail, zpass);
    (void)yagl_host_glStencilOpSeparate(face, fail, zfail, zpass);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform1f dispatcher. id = 116
 */
static bool yagl_func_glUniform1f(struct yagl_transport *t)
{
    GLint location;
    GLfloat x;
    location = yagl_transport_get_out_GLint(t);
    x = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform1f, GLint, GLfloat, location, x);
    (void)yagl_host_glUniform1f(location, x);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform1fv dispatcher. id = 117
 */
static bool yagl_func_glUniform1fv(struct yagl_transport *t)
{
    GLint location;
    const GLfloat *v;
    int32_t v_count;
    location = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&v, &v_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform1fv, GLint, void*, location, v);
    (void)yagl_host_glUniform1fv(location, v, v_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform1i dispatcher. id = 118
 */
static bool yagl_func_glUniform1i(struct yagl_transport *t)
{
    GLint location;
    GLint x;
    location = yagl_transport_get_out_GLint(t);
    x = yagl_transport_get_out_GLint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform1i, GLint, GLint, location, x);
    (void)yagl_host_glUniform1i(location, x);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform1iv dispatcher. id = 119
 */
static bool yagl_func_glUniform1iv(struct yagl_transport *t)
{
    GLint location;
    const GLint *v;
    int32_t v_count;
    location = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLint), (const void**)&v, &v_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform1iv, GLint, void*, location, v);
    (void)yagl_host_glUniform1iv(location, v, v_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform2f dispatcher. id = 120
 */
static bool yagl_func_glUniform2f(struct yagl_transport *t)
{
    GLint location;
    GLfloat x;
    GLfloat y;
    location = yagl_transport_get_out_GLint(t);
    x = yagl_transport_get_out_GLfloat(t);
    y = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform2f, GLint, GLfloat, GLfloat, location, x, y);
    (void)yagl_host_glUniform2f(location, x, y);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform2fv dispatcher. id = 121
 */
static bool yagl_func_glUniform2fv(struct yagl_transport *t)
{
    GLint location;
    const GLfloat *v;
    int32_t v_count;
    location = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&v, &v_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform2fv, GLint, void*, location, v);
    (void)yagl_host_glUniform2fv(location, v, v_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform2i dispatcher. id = 122
 */
static bool yagl_func_glUniform2i(struct yagl_transport *t)
{
    GLint location;
    GLint x;
    GLint y;
    location = yagl_transport_get_out_GLint(t);
    x = yagl_transport_get_out_GLint(t);
    y = yagl_transport_get_out_GLint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform2i, GLint, GLint, GLint, location, x, y);
    (void)yagl_host_glUniform2i(location, x, y);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform2iv dispatcher. id = 123
 */
static bool yagl_func_glUniform2iv(struct yagl_transport *t)
{
    GLint location;
    const GLint *v;
    int32_t v_count;
    location = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLint), (const void**)&v, &v_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform2iv, GLint, void*, location, v);
    (void)yagl_host_glUniform2iv(location, v, v_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform3f dispatcher. id = 124
 */
static bool yagl_func_glUniform3f(struct yagl_transport *t)
{
    GLint location;
    GLfloat x;
    GLfloat y;
    GLfloat z;
    location = yagl_transport_get_out_GLint(t);
    x = yagl_transport_get_out_GLfloat(t);
    y = yagl_transport_get_out_GLfloat(t);
    z = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glUniform3f, GLint, GLfloat, GLfloat, GLfloat, location, x, y, z);
    (void)yagl_host_glUniform3f(location, x, y, z);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform3fv dispatcher. id = 125
 */
static bool yagl_func_glUniform3fv(struct yagl_transport *t)
{
    GLint location;
    const GLfloat *v;
    int32_t v_count;
    location = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&v, &v_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform3fv, GLint, void*, location, v);
    (void)yagl_host_glUniform3fv(location, v, v_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform3i dispatcher. id = 126
 */
static bool yagl_func_glUniform3i(struct yagl_transport *t)
{
    GLint location;
    GLint x;
    GLint y;
    GLint z;
    location = yagl_transport_get_out_GLint(t);
    x = yagl_transport_get_out_GLint(t);
    y = yagl_transport_get_out_GLint(t);
    z = yagl_transport_get_out_GLint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glUniform3i, GLint, GLint, GLint, GLint, location, x, y, z);
    (void)yagl_host_glUniform3i(location, x, y, z);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform3iv dispatcher. id = 127
 */
static bool yagl_func_glUniform3iv(struct yagl_transport *t)
{
    GLint location;
    const GLint *v;
    int32_t v_count;
    location = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLint), (const void**)&v, &v_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform3iv, GLint, void*, location, v);
    (void)yagl_host_glUniform3iv(location, v, v_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform4f dispatcher. id = 128
 */
static bool yagl_func_glUniform4f(struct yagl_transport *t)
{
    GLint location;
    GLfloat x;
    GLfloat y;
    GLfloat z;
    GLfloat w;
    location = yagl_transport_get_out_GLint(t);
    x = yagl_transport_get_out_GLfloat(t);
    y = yagl_transport_get_out_GLfloat(t);
    z = yagl_transport_get_out_GLfloat(t);
    w = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glUniform4f, GLint, GLfloat, GLfloat, GLfloat, GLfloat, location, x, y, z, w);
    (void)yagl_host_glUniform4f(location, x, y, z, w);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform4fv dispatcher. id = 129
 */
static bool yagl_func_glUniform4fv(struct yagl_transport *t)
{
    GLint location;
    const GLfloat *v;
    int32_t v_count;
    location = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&v, &v_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform4fv, GLint, void*, location, v);
    (void)yagl_host_glUniform4fv(location, v, v_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform4i dispatcher. id = 130
 */
static bool yagl_func_glUniform4i(struct yagl_transport *t)
{
    GLint location;
    GLint x;
    GLint y;
    GLint z;
    GLint w;
    location = yagl_transport_get_out_GLint(t);
    x = yagl_transport_get_out_GLint(t);
    y = yagl_transport_get_out_GLint(t);
    z = yagl_transport_get_out_GLint(t);
    w = yagl_transport_get_out_GLint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glUniform4i, GLint, GLint, GLint, GLint, GLint, location, x, y, z, w);
    (void)yagl_host_glUniform4i(location, x, y, z, w);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniform4iv dispatcher. id = 131
 */
static bool yagl_func_glUniform4iv(struct yagl_transport *t)
{
    GLint location;
    const GLint *v;
    int32_t v_count;
    location = yagl_transport_get_out_GLint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLint), (const void**)&v, &v_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform4iv, GLint, void*, location, v);
    (void)yagl_host_glUniform4iv(location, v, v_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniformMatrix2fv dispatcher. id = 132
 */
static bool yagl_func_glUniformMatrix2fv(struct yagl_transport *t)
{
    GLint location;
    GLboolean transpose;
    const GLfloat *value;
    int32_t value_count;
    location = yagl_transport_get_out_GLint(t);
    transpose = yagl_transport_get_out_GLboolean(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&value, &value_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniformMatrix2fv, GLint, GLboolean, void*, location, transpose, value);
    (void)yagl_host_glUniformMatrix2fv(location, transpose, value, value_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniformMatrix3fv dispatcher. id = 133
 */
static bool yagl_func_glUniformMatrix3fv(struct yagl_transport *t)
{
    GLint location;
    GLboolean transpose;
    const GLfloat *value;
    int32_t value_count;
    location = yagl_transport_get_out_GLint(t);
    transpose = yagl_transport_get_out_GLboolean(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&value, &value_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniformMatrix3fv, GLint, GLboolean, void*, location, transpose, value);
    (void)yagl_host_glUniformMatrix3fv(location, transpose, value, value_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUniformMatrix4fv dispatcher. id = 134
 */
static bool yagl_func_glUniformMatrix4fv(struct yagl_transport *t)
{
    GLint location;
    GLboolean transpose;
    const GLfloat *value;
    int32_t value_count;
    location = yagl_transport_get_out_GLint(t);
    transpose = yagl_transport_get_out_GLboolean(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&value, &value_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniformMatrix4fv, GLint, GLboolean, void*, location, transpose, value);
    (void)yagl_host_glUniformMatrix4fv(location, transpose, value, value_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glUseProgram dispatcher. id = 135
 */
static bool yagl_func_glUseProgram(struct yagl_transport *t)
{
    GLuint program;
    program = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glUseProgram, GLuint, program);
    (void)yagl_host_glUseProgram(program);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glValidateProgram dispatcher. id = 136
 */
static bool yagl_func_glValidateProgram(struct yagl_transport *t)
{
    GLuint program;
    program = yagl_transport_get_out_GLuint(t);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glValidateProgram, GLuint, program);
    (void)yagl_host_glValidateProgram(program);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glVertexAttrib1f dispatcher. id = 137
 */
static bool yagl_func_glVertexAttrib1f(struct yagl_transport *t)
{
    GLuint indx;
    GLfloat x;
    indx = yagl_transport_get_out_GLuint(t);
    x = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glVertexAttrib1f, GLuint, GLfloat, indx, x);
    (void)yagl_host_glVertexAttrib1f(indx, x);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glVertexAttrib1fv dispatcher. id = 138
 */
static bool yagl_func_glVertexAttrib1fv(struct yagl_transport *t)
{
    GLuint indx;
    const GLfloat *values;
    int32_t values_count;
    indx = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&values, &values_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glVertexAttrib1fv, GLuint, void*, indx, values);
    (void)yagl_host_glVertexAttrib1fv(indx, values, values_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glVertexAttrib2f dispatcher. id = 139
 */
static bool yagl_func_glVertexAttrib2f(struct yagl_transport *t)
{
    GLuint indx;
    GLfloat x;
    GLfloat y;
    indx = yagl_transport_get_out_GLuint(t);
    x = yagl_transport_get_out_GLfloat(t);
    y = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glVertexAttrib2f, GLuint, GLfloat, GLfloat, indx, x, y);
    (void)yagl_host_glVertexAttrib2f(indx, x, y);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glVertexAttrib2fv dispatcher. id = 140
 */
static bool yagl_func_glVertexAttrib2fv(struct yagl_transport *t)
{
    GLuint indx;
    const GLfloat *values;
    int32_t values_count;
    indx = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&values, &values_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glVertexAttrib2fv, GLuint, void*, indx, values);
    (void)yagl_host_glVertexAttrib2fv(indx, values, values_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glVertexAttrib3f dispatcher. id = 141
 */
static bool yagl_func_glVertexAttrib3f(struct yagl_transport *t)
{
    GLuint indx;
    GLfloat x;
    GLfloat y;
    GLfloat z;
    indx = yagl_transport_get_out_GLuint(t);
    x = yagl_transport_get_out_GLfloat(t);
    y = yagl_transport_get_out_GLfloat(t);
    z = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glVertexAttrib3f, GLuint, GLfloat, GLfloat, GLfloat, indx, x, y, z);
    (void)yagl_host_glVertexAttrib3f(indx, x, y, z);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glVertexAttrib3fv dispatcher. id = 142
 */
static bool yagl_func_glVertexAttrib3fv(struct yagl_transport *t)
{
    GLuint indx;
    const GLfloat *values;
    int32_t values_count;
    indx = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&values, &values_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glVertexAttrib3fv, GLuint, void*, indx, values);
    (void)yagl_host_glVertexAttrib3fv(indx, values, values_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glVertexAttrib4f dispatcher. id = 143
 */
static bool yagl_func_glVertexAttrib4f(struct yagl_transport *t)
{
    GLuint indx;
    GLfloat x;
    GLfloat y;
    GLfloat z;
    GLfloat w;
    indx = yagl_transport_get_out_GLuint(t);
    x = yagl_transport_get_out_GLfloat(t);
    y = yagl_transport_get_out_GLfloat(t);
    z = yagl_transport_get_out_GLfloat(t);
    w = yagl_transport_get_out_GLfloat(t);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glVertexAttrib4f, GLuint, GLfloat, GLfloat, GLfloat, GLfloat, indx, x, y, z, w);
    (void)yagl_host_glVertexAttrib4f(indx, x, y, z, w);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glVertexAttrib4fv dispatcher. id = 144
 */
static bool yagl_func_glVertexAttrib4fv(struct yagl_transport *t)
{
    GLuint indx;
    const GLfloat *values;
    int32_t values_count;
    indx = yagl_transport_get_out_GLuint(t);
    if (!yagl_transport_get_out_array(t, sizeof(GLfloat), (const void**)&values, &values_count)) {
        return false;
    }
    YAGL_LOG_FUNC_ENTER_SPLIT2(glVertexAttrib4fv, GLuint, void*, indx, values);
    (void)yagl_host_glVertexAttrib4fv(indx, values, values_count);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

/*
 * glVertexAttribPointer dispatcher. id = 145
 */
static bool yagl_func_glVertexAttribPointer(struct yagl_transport *t)
{
    GLuint indx;
    GLint size;
    GLenum type;
    GLboolean normalized;
    GLsizei stride;
    target_ulong ptr;
    indx = yagl_transport_get_out_GLuint(t);
    size = yagl_transport_get_out_GLint(t);
    type = yagl_transport_get_out_GLenum(t);
    normalized = yagl_transport_get_out_GLboolean(t);
    stride = yagl_transport_get_out_GLsizei(t);
    ptr = yagl_transport_get_out_va(t);
    YAGL_LOG_FUNC_ENTER_SPLIT6(glVertexAttribPointer, GLuint, GLint, GLenum, GLboolean, GLsizei, target_ulong, indx, size, type, normalized, stride, ptr);
    (void)yagl_host_glVertexAttribPointer(indx, size, type, normalized, stride, ptr);
    YAGL_LOG_FUNC_EXIT(NULL);

    return true;
}

const uint32_t yagl_gles2_api_num_funcs = 145;

yagl_api_func yagl_gles2_api_funcs[] = {
    &yagl_func_glActiveTexture,
    &yagl_func_glBindBuffer,
    &yagl_func_glBindFramebuffer,
    &yagl_func_glBindRenderbuffer,
    &yagl_func_glBindTexture,
    &yagl_func_glBlendEquation,
    &yagl_func_glBlendEquationSeparate,
    &yagl_func_glBlendFunc,
    &yagl_func_glBlendFuncSeparate,
    &yagl_func_glBufferData,
    &yagl_func_glBufferSubData,
    &yagl_func_glCheckFramebufferStatus,
    &yagl_func_glClear,
    &yagl_func_glClearColor,
    &yagl_func_glClearDepthf,
    &yagl_func_glClearStencil,
    &yagl_func_glColorMask,
    &yagl_func_glCompressedTexImage2D,
    &yagl_func_glCompressedTexSubImage2D,
    &yagl_func_glCopyTexImage2D,
    &yagl_func_glCopyTexSubImage2D,
    &yagl_func_glCullFace,
    &yagl_func_glDeleteBuffers,
    &yagl_func_glDeleteFramebuffers,
    &yagl_func_glDeleteRenderbuffers,
    &yagl_func_glDeleteTextures,
    &yagl_func_glDepthFunc,
    &yagl_func_glDepthMask,
    &yagl_func_glDepthRangef,
    &yagl_func_glDisable,
    &yagl_func_glDrawArrays,
    &yagl_func_glEGLImageTargetTexture2DOES,
    &yagl_func_glEnable,
    &yagl_func_glFlush,
    &yagl_func_glFramebufferTexture2D,
    &yagl_func_glFramebufferRenderbuffer,
    &yagl_func_glFrontFace,
    &yagl_func_glGenBuffers,
    &yagl_func_glGenerateMipmap,
    &yagl_func_glGenFramebuffers,
    &yagl_func_glGenRenderbuffers,
    &yagl_func_glGenTextures,
    &yagl_func_glGetBooleanv,
    &yagl_func_glGetBufferParameteriv,
    &yagl_func_glGetError,
    &yagl_func_glGetFloatv,
    &yagl_func_glGetFramebufferAttachmentParameteriv,
    &yagl_func_glGetIntegerv,
    &yagl_func_glGetRenderbufferParameteriv,
    &yagl_func_glGetTexParameterfv,
    &yagl_func_glGetTexParameteriv,
    &yagl_func_glHint,
    &yagl_func_glIsBuffer,
    &yagl_func_glIsEnabled,
    &yagl_func_glIsFramebuffer,
    &yagl_func_glIsRenderbuffer,
    &yagl_func_glIsTexture,
    &yagl_func_glLineWidth,
    &yagl_func_glPixelStorei,
    &yagl_func_glPolygonOffset,
    &yagl_func_glReadPixels,
    &yagl_func_glRenderbufferStorage,
    &yagl_func_glSampleCoverage,
    &yagl_func_glScissor,
    &yagl_func_glStencilFunc,
    &yagl_func_glStencilMask,
    &yagl_func_glStencilOp,
    &yagl_func_glTexImage2D,
    &yagl_func_glTexParameterf,
    &yagl_func_glTexParameterfv,
    &yagl_func_glTexParameteri,
    &yagl_func_glTexParameteriv,
    &yagl_func_glTexSubImage2D,
    &yagl_func_glViewport,
    &yagl_func_glTransferArrayYAGL,
    &yagl_func_glDrawElementsIndicesYAGL,
    &yagl_func_glDrawElementsOffsetYAGL,
    &yagl_func_glGetExtensionStringYAGL,
    &yagl_func_glGetVertexAttribRangeYAGL,
    &yagl_func_glAttachShader,
    &yagl_func_glBindAttribLocation,
    &yagl_func_glBlendColor,
    &yagl_func_glCompileShader,
    &yagl_func_glCreateProgram,
    &yagl_func_glCreateShader,
    &yagl_func_glDeleteProgram,
    &yagl_func_glDeleteShader,
    &yagl_func_glDetachShader,
    &yagl_func_glDisableVertexAttribArray,
    &yagl_func_glEnableVertexAttribArray,
    &yagl_func_glGetActiveAttrib,
    &yagl_func_glGetActiveUniform,
    &yagl_func_glGetAttachedShaders,
    &yagl_func_glGetAttribLocation,
    &yagl_func_glGetProgramiv,
    &yagl_func_glGetProgramInfoLog,
    &yagl_func_glGetShaderiv,
    &yagl_func_glGetShaderInfoLog,
    &yagl_func_glGetShaderPrecisionFormat,
    &yagl_func_glGetShaderSource,
    &yagl_func_glGetUniformfv,
    &yagl_func_glGetUniformiv,
    &yagl_func_glGetUniformLocation,
    &yagl_func_glGetVertexAttribfv,
    &yagl_func_glGetVertexAttribiv,
    &yagl_func_glGetVertexAttribPointerv,
    &yagl_func_glIsProgram,
    &yagl_func_glIsShader,
    &yagl_func_glLinkProgram,
    &yagl_func_glReleaseShaderCompiler,
    &yagl_func_glShaderBinary,
    &yagl_func_glShaderSource,
    &yagl_func_glStencilFuncSeparate,
    &yagl_func_glStencilMaskSeparate,
    &yagl_func_glStencilOpSeparate,
    &yagl_func_glUniform1f,
    &yagl_func_glUniform1fv,
    &yagl_func_glUniform1i,
    &yagl_func_glUniform1iv,
    &yagl_func_glUniform2f,
    &yagl_func_glUniform2fv,
    &yagl_func_glUniform2i,
    &yagl_func_glUniform2iv,
    &yagl_func_glUniform3f,
    &yagl_func_glUniform3fv,
    &yagl_func_glUniform3i,
    &yagl_func_glUniform3iv,
    &yagl_func_glUniform4f,
    &yagl_func_glUniform4fv,
    &yagl_func_glUniform4i,
    &yagl_func_glUniform4iv,
    &yagl_func_glUniformMatrix2fv,
    &yagl_func_glUniformMatrix3fv,
    &yagl_func_glUniformMatrix4fv,
    &yagl_func_glUseProgram,
    &yagl_func_glValidateProgram,
    &yagl_func_glVertexAttrib1f,
    &yagl_func_glVertexAttrib1fv,
    &yagl_func_glVertexAttrib2f,
    &yagl_func_glVertexAttrib2fv,
    &yagl_func_glVertexAttrib3f,
    &yagl_func_glVertexAttrib3fv,
    &yagl_func_glVertexAttrib4f,
    &yagl_func_glVertexAttrib4fv,
    &yagl_func_glVertexAttribPointer,
};
