/*
 * Generated by gen-yagl-calls.sh, do not modify!
 */
#include "yagl_gles2_calls.h"
#include "yagl_host_gles2_calls.h"
#include "yagl_marshal_gl.h"
#include "yagl_thread.h"
#include "yagl_process.h"
#include "yagl_log.h"

/*
 * glActiveTexture dispatcher. id = 1
 */
static bool yagl_func_glActiveTexture(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum texture = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glActiveTexture, GLenum, texture);
    bool res = yagl_host_glActiveTexture(texture);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBindBuffer dispatcher. id = 2
 */
static bool yagl_func_glBindBuffer(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLuint buffer = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBindBuffer, GLenum, GLuint, target, buffer);
    bool res = yagl_host_glBindBuffer(target, buffer);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBindFramebuffer dispatcher. id = 3
 */
static bool yagl_func_glBindFramebuffer(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLuint framebuffer = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBindFramebuffer, GLenum, GLuint, target, framebuffer);
    bool res = yagl_host_glBindFramebuffer(target, framebuffer);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBindRenderbuffer dispatcher. id = 4
 */
static bool yagl_func_glBindRenderbuffer(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLuint renderbuffer = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBindRenderbuffer, GLenum, GLuint, target, renderbuffer);
    bool res = yagl_host_glBindRenderbuffer(target, renderbuffer);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBindTexture dispatcher. id = 5
 */
static bool yagl_func_glBindTexture(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLuint texture = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBindTexture, GLenum, GLuint, target, texture);
    bool res = yagl_host_glBindTexture(target, texture);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBlendEquation dispatcher. id = 6
 */
static bool yagl_func_glBlendEquation(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum mode = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glBlendEquation, GLenum, mode);
    bool res = yagl_host_glBlendEquation(mode);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBlendEquationSeparate dispatcher. id = 7
 */
static bool yagl_func_glBlendEquationSeparate(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum modeRGB = yagl_marshal_get_GLenum(out_buff);
    GLenum modeAlpha = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBlendEquationSeparate, GLenum, GLenum, modeRGB, modeAlpha);
    bool res = yagl_host_glBlendEquationSeparate(modeRGB, modeAlpha);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBlendFunc dispatcher. id = 8
 */
static bool yagl_func_glBlendFunc(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum sfactor = yagl_marshal_get_GLenum(out_buff);
    GLenum dfactor = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glBlendFunc, GLenum, GLenum, sfactor, dfactor);
    bool res = yagl_host_glBlendFunc(sfactor, dfactor);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBlendFuncSeparate dispatcher. id = 9
 */
static bool yagl_func_glBlendFuncSeparate(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum srcRGB = yagl_marshal_get_GLenum(out_buff);
    GLenum dstRGB = yagl_marshal_get_GLenum(out_buff);
    GLenum srcAlpha = yagl_marshal_get_GLenum(out_buff);
    GLenum dstAlpha = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glBlendFuncSeparate, GLenum, GLenum, GLenum, GLenum, srcRGB, dstRGB, srcAlpha, dstAlpha);
    bool res = yagl_host_glBlendFuncSeparate(srcRGB, dstRGB, srcAlpha, dstAlpha);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBufferData dispatcher. id = 10
 */
static bool yagl_func_glBufferData(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLsizeiptr size = yagl_marshal_get_GLsizeiptr(out_buff);
    target_ulong data = yagl_marshal_get_ptr(out_buff);
    GLenum usage = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glBufferData, GLenum, GLsizeiptr, target_ulong, GLenum, target, size, data, usage);
    bool res = yagl_host_glBufferData(target, size, data, usage);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBufferSubData dispatcher. id = 11
 */
static bool yagl_func_glBufferSubData(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLintptr offset = yagl_marshal_get_GLintptr(out_buff);
    GLsizeiptr size = yagl_marshal_get_GLsizeiptr(out_buff);
    target_ulong data = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glBufferSubData, GLenum, GLintptr, GLsizeiptr, target_ulong, target, offset, size, data);
    bool res = yagl_host_glBufferSubData(target, offset, size, data);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glCheckFramebufferStatus dispatcher. id = 12
 */
static bool yagl_func_glCheckFramebufferStatus(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glCheckFramebufferStatus, GLenum, target);
    GLenum retval;
    bool res = yagl_host_glCheckFramebufferStatus(&retval, target);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLenum, retval);
    yagl_marshal_put_GLenum(&in_buff, retval);
    return true;
}

/*
 * glClear dispatcher. id = 13
 */
static bool yagl_func_glClear(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLbitfield mask = yagl_marshal_get_GLbitfield(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glClear, GLbitfield, mask);
    bool res = yagl_host_glClear(mask);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glClearColor dispatcher. id = 14
 */
static bool yagl_func_glClearColor(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLclampf red = yagl_marshal_get_GLclampf(out_buff);
    GLclampf green = yagl_marshal_get_GLclampf(out_buff);
    GLclampf blue = yagl_marshal_get_GLclampf(out_buff);
    GLclampf alpha = yagl_marshal_get_GLclampf(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glClearColor, GLclampf, GLclampf, GLclampf, GLclampf, red, green, blue, alpha);
    bool res = yagl_host_glClearColor(red, green, blue, alpha);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glClearDepthf dispatcher. id = 15
 */
static bool yagl_func_glClearDepthf(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLclampf depth = yagl_marshal_get_GLclampf(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glClearDepthf, GLclampf, depth);
    bool res = yagl_host_glClearDepthf(depth);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glClearStencil dispatcher. id = 16
 */
static bool yagl_func_glClearStencil(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint s = yagl_marshal_get_GLint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glClearStencil, GLint, s);
    bool res = yagl_host_glClearStencil(s);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glColorMask dispatcher. id = 17
 */
static bool yagl_func_glColorMask(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLboolean red = yagl_marshal_get_GLboolean(out_buff);
    GLboolean green = yagl_marshal_get_GLboolean(out_buff);
    GLboolean blue = yagl_marshal_get_GLboolean(out_buff);
    GLboolean alpha = yagl_marshal_get_GLboolean(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glColorMask, GLboolean, GLboolean, GLboolean, GLboolean, red, green, blue, alpha);
    bool res = yagl_host_glColorMask(red, green, blue, alpha);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glCompressedTexImage2D dispatcher. id = 18
 */
static bool yagl_func_glCompressedTexImage2D(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLint level = yagl_marshal_get_GLint(out_buff);
    GLenum internalformat = yagl_marshal_get_GLenum(out_buff);
    GLsizei width = yagl_marshal_get_GLsizei(out_buff);
    GLsizei height = yagl_marshal_get_GLsizei(out_buff);
    GLint border = yagl_marshal_get_GLint(out_buff);
    GLsizei imageSize = yagl_marshal_get_GLsizei(out_buff);
    target_ulong data = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT8(glCompressedTexImage2D, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, target_ulong, target, level, internalformat, width, height, border, imageSize, data);
    bool res = yagl_host_glCompressedTexImage2D(target, level, internalformat, width, height, border, imageSize, data);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glCompressedTexSubImage2D dispatcher. id = 19
 */
static bool yagl_func_glCompressedTexSubImage2D(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLint level = yagl_marshal_get_GLint(out_buff);
    GLint xoffset = yagl_marshal_get_GLint(out_buff);
    GLint yoffset = yagl_marshal_get_GLint(out_buff);
    GLsizei width = yagl_marshal_get_GLsizei(out_buff);
    GLsizei height = yagl_marshal_get_GLsizei(out_buff);
    GLenum format = yagl_marshal_get_GLenum(out_buff);
    GLsizei imageSize = yagl_marshal_get_GLsizei(out_buff);
    target_ulong data = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT9(glCompressedTexSubImage2D, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, target_ulong, target, level, xoffset, yoffset, width, height, format, imageSize, data);
    bool res = yagl_host_glCompressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, data);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glCopyTexImage2D dispatcher. id = 20
 */
static bool yagl_func_glCopyTexImage2D(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLint level = yagl_marshal_get_GLint(out_buff);
    GLenum internalformat = yagl_marshal_get_GLenum(out_buff);
    GLint x = yagl_marshal_get_GLint(out_buff);
    GLint y = yagl_marshal_get_GLint(out_buff);
    GLsizei width = yagl_marshal_get_GLsizei(out_buff);
    GLsizei height = yagl_marshal_get_GLsizei(out_buff);
    GLint border = yagl_marshal_get_GLint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT8(glCopyTexImage2D, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint, target, level, internalformat, x, y, width, height, border);
    bool res = yagl_host_glCopyTexImage2D(target, level, internalformat, x, y, width, height, border);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glCopyTexSubImage2D dispatcher. id = 21
 */
static bool yagl_func_glCopyTexSubImage2D(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLint level = yagl_marshal_get_GLint(out_buff);
    GLint xoffset = yagl_marshal_get_GLint(out_buff);
    GLint yoffset = yagl_marshal_get_GLint(out_buff);
    GLint x = yagl_marshal_get_GLint(out_buff);
    GLint y = yagl_marshal_get_GLint(out_buff);
    GLsizei width = yagl_marshal_get_GLsizei(out_buff);
    GLsizei height = yagl_marshal_get_GLsizei(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT8(glCopyTexSubImage2D, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, target, level, xoffset, yoffset, x, y, width, height);
    bool res = yagl_host_glCopyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glCullFace dispatcher. id = 22
 */
static bool yagl_func_glCullFace(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum mode = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glCullFace, GLenum, mode);
    bool res = yagl_host_glCullFace(mode);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDeleteBuffers dispatcher. id = 23
 */
static bool yagl_func_glDeleteBuffers(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLsizei n = yagl_marshal_get_GLsizei(out_buff);
    target_ulong buffers = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glDeleteBuffers, GLsizei, target_ulong, n, buffers);
    bool res = yagl_host_glDeleteBuffers(n, buffers);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDeleteFramebuffers dispatcher. id = 24
 */
static bool yagl_func_glDeleteFramebuffers(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLsizei n = yagl_marshal_get_GLsizei(out_buff);
    target_ulong framebuffers = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glDeleteFramebuffers, GLsizei, target_ulong, n, framebuffers);
    bool res = yagl_host_glDeleteFramebuffers(n, framebuffers);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDeleteRenderbuffers dispatcher. id = 25
 */
static bool yagl_func_glDeleteRenderbuffers(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLsizei n = yagl_marshal_get_GLsizei(out_buff);
    target_ulong renderbuffers = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glDeleteRenderbuffers, GLsizei, target_ulong, n, renderbuffers);
    bool res = yagl_host_glDeleteRenderbuffers(n, renderbuffers);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDeleteTextures dispatcher. id = 26
 */
static bool yagl_func_glDeleteTextures(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLsizei n = yagl_marshal_get_GLsizei(out_buff);
    target_ulong textures = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glDeleteTextures, GLsizei, target_ulong, n, textures);
    bool res = yagl_host_glDeleteTextures(n, textures);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDepthFunc dispatcher. id = 27
 */
static bool yagl_func_glDepthFunc(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum func = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDepthFunc, GLenum, func);
    bool res = yagl_host_glDepthFunc(func);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDepthMask dispatcher. id = 28
 */
static bool yagl_func_glDepthMask(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLboolean flag = yagl_marshal_get_GLboolean(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDepthMask, GLboolean, flag);
    bool res = yagl_host_glDepthMask(flag);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDepthRangef dispatcher. id = 29
 */
static bool yagl_func_glDepthRangef(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLclampf zNear = yagl_marshal_get_GLclampf(out_buff);
    GLclampf zFar = yagl_marshal_get_GLclampf(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glDepthRangef, GLclampf, GLclampf, zNear, zFar);
    bool res = yagl_host_glDepthRangef(zNear, zFar);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDisable dispatcher. id = 30
 */
static bool yagl_func_glDisable(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum cap = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDisable, GLenum, cap);
    bool res = yagl_host_glDisable(cap);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDrawArrays dispatcher. id = 31
 */
static bool yagl_func_glDrawArrays(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum mode = yagl_marshal_get_GLenum(out_buff);
    GLint first = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glDrawArrays, GLenum, GLint, GLsizei, mode, first, count);
    bool res = yagl_host_glDrawArrays(mode, first, count);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDrawElements dispatcher. id = 32
 */
static bool yagl_func_glDrawElements(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum mode = yagl_marshal_get_GLenum(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    GLenum type = yagl_marshal_get_GLenum(out_buff);
    target_ulong indices = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glDrawElements, GLenum, GLsizei, GLenum, target_ulong, mode, count, type, indices);
    bool res = yagl_host_glDrawElements(mode, count, type, indices);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glEGLImageTargetTexture2DOES dispatcher. id = 33
 */
static bool yagl_func_glEGLImageTargetTexture2DOES(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    yagl_host_handle image = yagl_marshal_get_host_handle(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glEGLImageTargetTexture2DOES, GLenum, yagl_host_handle, target, image);
    bool res = yagl_host_glEGLImageTargetTexture2DOES(target, image);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glEnable dispatcher. id = 34
 */
static bool yagl_func_glEnable(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum cap = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glEnable, GLenum, cap);
    bool res = yagl_host_glEnable(cap);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glFinish dispatcher. id = 35
 */
static bool yagl_func_glFinish(uint8_t **out_buff,
    uint8_t *in_buff)
{
    YAGL_LOG_FUNC_ENTER_SPLIT0(glFinish);
    bool res = yagl_host_glFinish();
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glFlush dispatcher. id = 36
 */
static bool yagl_func_glFlush(uint8_t **out_buff,
    uint8_t *in_buff)
{
    YAGL_LOG_FUNC_ENTER_SPLIT0(glFlush);
    bool res = yagl_host_glFlush();
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glFramebufferTexture2D dispatcher. id = 37
 */
static bool yagl_func_glFramebufferTexture2D(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum attachment = yagl_marshal_get_GLenum(out_buff);
    GLenum textarget = yagl_marshal_get_GLenum(out_buff);
    GLuint texture = yagl_marshal_get_GLuint(out_buff);
    GLint level = yagl_marshal_get_GLint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glFramebufferTexture2D, GLenum, GLenum, GLenum, GLuint, GLint, target, attachment, textarget, texture, level);
    bool res = yagl_host_glFramebufferTexture2D(target, attachment, textarget, texture, level);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glFramebufferRenderbuffer dispatcher. id = 38
 */
static bool yagl_func_glFramebufferRenderbuffer(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum attachment = yagl_marshal_get_GLenum(out_buff);
    GLenum renderbuffertarget = yagl_marshal_get_GLenum(out_buff);
    GLuint renderbuffer = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glFramebufferRenderbuffer, GLenum, GLenum, GLenum, GLuint, target, attachment, renderbuffertarget, renderbuffer);
    bool res = yagl_host_glFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glFrontFace dispatcher. id = 39
 */
static bool yagl_func_glFrontFace(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum mode = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glFrontFace, GLenum, mode);
    bool res = yagl_host_glFrontFace(mode);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGenBuffers dispatcher. id = 40
 */
static bool yagl_func_glGenBuffers(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLsizei n = yagl_marshal_get_GLsizei(out_buff);
    target_ulong buffers = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGenBuffers, GLsizei, target_ulong, n, buffers);
    bool res = yagl_host_glGenBuffers(n, buffers);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGenerateMipmap dispatcher. id = 41
 */
static bool yagl_func_glGenerateMipmap(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glGenerateMipmap, GLenum, target);
    bool res = yagl_host_glGenerateMipmap(target);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGenFramebuffers dispatcher. id = 42
 */
static bool yagl_func_glGenFramebuffers(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLsizei n = yagl_marshal_get_GLsizei(out_buff);
    target_ulong framebuffers = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGenFramebuffers, GLsizei, target_ulong, n, framebuffers);
    bool res = yagl_host_glGenFramebuffers(n, framebuffers);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGenRenderbuffers dispatcher. id = 43
 */
static bool yagl_func_glGenRenderbuffers(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLsizei n = yagl_marshal_get_GLsizei(out_buff);
    target_ulong renderbuffers = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGenRenderbuffers, GLsizei, target_ulong, n, renderbuffers);
    bool res = yagl_host_glGenRenderbuffers(n, renderbuffers);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGenTextures dispatcher. id = 44
 */
static bool yagl_func_glGenTextures(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLsizei n = yagl_marshal_get_GLsizei(out_buff);
    target_ulong textures = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGenTextures, GLsizei, target_ulong, n, textures);
    bool res = yagl_host_glGenTextures(n, textures);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetBooleanv dispatcher. id = 45
 */
static bool yagl_func_glGetBooleanv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetBooleanv, GLenum, target_ulong, pname, params);
    bool res = yagl_host_glGetBooleanv(pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetBufferParameteriv dispatcher. id = 46
 */
static bool yagl_func_glGetBufferParameteriv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetBufferParameteriv, GLenum, GLenum, target_ulong, target, pname, params);
    bool res = yagl_host_glGetBufferParameteriv(target, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetError dispatcher. id = 47
 */
static bool yagl_func_glGetError(uint8_t **out_buff,
    uint8_t *in_buff)
{
    YAGL_LOG_FUNC_ENTER_SPLIT0(glGetError);
    GLenum retval;
    bool res = yagl_host_glGetError(&retval);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLenum, retval);
    yagl_marshal_put_GLenum(&in_buff, retval);
    return true;
}

/*
 * glGetFloatv dispatcher. id = 48
 */
static bool yagl_func_glGetFloatv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetFloatv, GLenum, target_ulong, pname, params);
    bool res = yagl_host_glGetFloatv(pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetFramebufferAttachmentParameteriv dispatcher. id = 49
 */
static bool yagl_func_glGetFramebufferAttachmentParameteriv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum attachment = yagl_marshal_get_GLenum(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glGetFramebufferAttachmentParameteriv, GLenum, GLenum, GLenum, target_ulong, target, attachment, pname, params);
    bool res = yagl_host_glGetFramebufferAttachmentParameteriv(target, attachment, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetIntegerv dispatcher. id = 50
 */
static bool yagl_func_glGetIntegerv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetIntegerv, GLenum, target_ulong, pname, params);
    bool res = yagl_host_glGetIntegerv(pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetRenderbufferParameteriv dispatcher. id = 51
 */
static bool yagl_func_glGetRenderbufferParameteriv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetRenderbufferParameteriv, GLenum, GLenum, target_ulong, target, pname, params);
    bool res = yagl_host_glGetRenderbufferParameteriv(target, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetTexParameterfv dispatcher. id = 52
 */
static bool yagl_func_glGetTexParameterfv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetTexParameterfv, GLenum, GLenum, target_ulong, target, pname, params);
    bool res = yagl_host_glGetTexParameterfv(target, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetTexParameteriv dispatcher. id = 53
 */
static bool yagl_func_glGetTexParameteriv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetTexParameteriv, GLenum, GLenum, target_ulong, target, pname, params);
    bool res = yagl_host_glGetTexParameteriv(target, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glHint dispatcher. id = 54
 */
static bool yagl_func_glHint(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum mode = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glHint, GLenum, GLenum, target, mode);
    bool res = yagl_host_glHint(target, mode);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glIsBuffer dispatcher. id = 55
 */
static bool yagl_func_glIsBuffer(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint buffer = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsBuffer, GLuint, buffer);
    GLboolean retval;
    bool res = yagl_host_glIsBuffer(&retval, buffer);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, retval);
    yagl_marshal_put_GLboolean(&in_buff, retval);
    return true;
}

/*
 * glIsEnabled dispatcher. id = 56
 */
static bool yagl_func_glIsEnabled(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum cap = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsEnabled, GLenum, cap);
    GLboolean retval;
    bool res = yagl_host_glIsEnabled(&retval, cap);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, retval);
    yagl_marshal_put_GLboolean(&in_buff, retval);
    return true;
}

/*
 * glIsFramebuffer dispatcher. id = 57
 */
static bool yagl_func_glIsFramebuffer(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint framebuffer = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsFramebuffer, GLuint, framebuffer);
    GLboolean retval;
    bool res = yagl_host_glIsFramebuffer(&retval, framebuffer);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, retval);
    yagl_marshal_put_GLboolean(&in_buff, retval);
    return true;
}

/*
 * glIsRenderbuffer dispatcher. id = 58
 */
static bool yagl_func_glIsRenderbuffer(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint renderbuffer = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsRenderbuffer, GLuint, renderbuffer);
    GLboolean retval;
    bool res = yagl_host_glIsRenderbuffer(&retval, renderbuffer);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, retval);
    yagl_marshal_put_GLboolean(&in_buff, retval);
    return true;
}

/*
 * glIsTexture dispatcher. id = 59
 */
static bool yagl_func_glIsTexture(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint texture = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsTexture, GLuint, texture);
    GLboolean retval;
    bool res = yagl_host_glIsTexture(&retval, texture);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, retval);
    yagl_marshal_put_GLboolean(&in_buff, retval);
    return true;
}

/*
 * glLineWidth dispatcher. id = 60
 */
static bool yagl_func_glLineWidth(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLfloat width = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glLineWidth, GLfloat, width);
    bool res = yagl_host_glLineWidth(width);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glPixelStorei dispatcher. id = 61
 */
static bool yagl_func_glPixelStorei(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    GLint param = yagl_marshal_get_GLint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glPixelStorei, GLenum, GLint, pname, param);
    bool res = yagl_host_glPixelStorei(pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glPolygonOffset dispatcher. id = 62
 */
static bool yagl_func_glPolygonOffset(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLfloat factor = yagl_marshal_get_GLfloat(out_buff);
    GLfloat units = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glPolygonOffset, GLfloat, GLfloat, factor, units);
    bool res = yagl_host_glPolygonOffset(factor, units);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glReadPixels dispatcher. id = 63
 */
static bool yagl_func_glReadPixels(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint x = yagl_marshal_get_GLint(out_buff);
    GLint y = yagl_marshal_get_GLint(out_buff);
    GLsizei width = yagl_marshal_get_GLsizei(out_buff);
    GLsizei height = yagl_marshal_get_GLsizei(out_buff);
    GLenum format = yagl_marshal_get_GLenum(out_buff);
    GLenum type = yagl_marshal_get_GLenum(out_buff);
    target_ulong pixels = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT7(glReadPixels, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, target_ulong, x, y, width, height, format, type, pixels);
    bool res = yagl_host_glReadPixels(x, y, width, height, format, type, pixels);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glRenderbufferStorage dispatcher. id = 64
 */
static bool yagl_func_glRenderbufferStorage(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum internalformat = yagl_marshal_get_GLenum(out_buff);
    GLsizei width = yagl_marshal_get_GLsizei(out_buff);
    GLsizei height = yagl_marshal_get_GLsizei(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glRenderbufferStorage, GLenum, GLenum, GLsizei, GLsizei, target, internalformat, width, height);
    bool res = yagl_host_glRenderbufferStorage(target, internalformat, width, height);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glSampleCoverage dispatcher. id = 65
 */
static bool yagl_func_glSampleCoverage(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLclampf value = yagl_marshal_get_GLclampf(out_buff);
    GLboolean invert = yagl_marshal_get_GLboolean(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glSampleCoverage, GLclampf, GLboolean, value, invert);
    bool res = yagl_host_glSampleCoverage(value, invert);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glScissor dispatcher. id = 66
 */
static bool yagl_func_glScissor(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint x = yagl_marshal_get_GLint(out_buff);
    GLint y = yagl_marshal_get_GLint(out_buff);
    GLsizei width = yagl_marshal_get_GLsizei(out_buff);
    GLsizei height = yagl_marshal_get_GLsizei(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glScissor, GLint, GLint, GLsizei, GLsizei, x, y, width, height);
    bool res = yagl_host_glScissor(x, y, width, height);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glStencilFunc dispatcher. id = 67
 */
static bool yagl_func_glStencilFunc(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum func = yagl_marshal_get_GLenum(out_buff);
    GLint ref = yagl_marshal_get_GLint(out_buff);
    GLuint mask = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glStencilFunc, GLenum, GLint, GLuint, func, ref, mask);
    bool res = yagl_host_glStencilFunc(func, ref, mask);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glStencilMask dispatcher. id = 68
 */
static bool yagl_func_glStencilMask(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint mask = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glStencilMask, GLuint, mask);
    bool res = yagl_host_glStencilMask(mask);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glStencilOp dispatcher. id = 69
 */
static bool yagl_func_glStencilOp(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum fail = yagl_marshal_get_GLenum(out_buff);
    GLenum zfail = yagl_marshal_get_GLenum(out_buff);
    GLenum zpass = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glStencilOp, GLenum, GLenum, GLenum, fail, zfail, zpass);
    bool res = yagl_host_glStencilOp(fail, zfail, zpass);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glTexImage2D dispatcher. id = 70
 */
static bool yagl_func_glTexImage2D(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLint level = yagl_marshal_get_GLint(out_buff);
    GLint internalformat = yagl_marshal_get_GLint(out_buff);
    GLsizei width = yagl_marshal_get_GLsizei(out_buff);
    GLsizei height = yagl_marshal_get_GLsizei(out_buff);
    GLint border = yagl_marshal_get_GLint(out_buff);
    GLenum format = yagl_marshal_get_GLenum(out_buff);
    GLenum type = yagl_marshal_get_GLenum(out_buff);
    target_ulong pixels = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT9(glTexImage2D, GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, target_ulong, target, level, internalformat, width, height, border, format, type, pixels);
    bool res = yagl_host_glTexImage2D(target, level, internalformat, width, height, border, format, type, pixels);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glTexParameterf dispatcher. id = 71
 */
static bool yagl_func_glTexParameterf(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    GLfloat param = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glTexParameterf, GLenum, GLenum, GLfloat, target, pname, param);
    bool res = yagl_host_glTexParameterf(target, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glTexParameterfv dispatcher. id = 72
 */
static bool yagl_func_glTexParameterfv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glTexParameterfv, GLenum, GLenum, target_ulong, target, pname, params);
    bool res = yagl_host_glTexParameterfv(target, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glTexParameteri dispatcher. id = 73
 */
static bool yagl_func_glTexParameteri(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    GLint param = yagl_marshal_get_GLint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glTexParameteri, GLenum, GLenum, GLint, target, pname, param);
    bool res = yagl_host_glTexParameteri(target, pname, param);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glTexParameteriv dispatcher. id = 74
 */
static bool yagl_func_glTexParameteriv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glTexParameteriv, GLenum, GLenum, target_ulong, target, pname, params);
    bool res = yagl_host_glTexParameteriv(target, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glTexSubImage2D dispatcher. id = 75
 */
static bool yagl_func_glTexSubImage2D(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum target = yagl_marshal_get_GLenum(out_buff);
    GLint level = yagl_marshal_get_GLint(out_buff);
    GLint xoffset = yagl_marshal_get_GLint(out_buff);
    GLint yoffset = yagl_marshal_get_GLint(out_buff);
    GLsizei width = yagl_marshal_get_GLsizei(out_buff);
    GLsizei height = yagl_marshal_get_GLsizei(out_buff);
    GLenum format = yagl_marshal_get_GLenum(out_buff);
    GLenum type = yagl_marshal_get_GLenum(out_buff);
    target_ulong pixels = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT9(glTexSubImage2D, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, target_ulong, target, level, xoffset, yoffset, width, height, format, type, pixels);
    bool res = yagl_host_glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glViewport dispatcher. id = 76
 */
static bool yagl_func_glViewport(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint x = yagl_marshal_get_GLint(out_buff);
    GLint y = yagl_marshal_get_GLint(out_buff);
    GLsizei width = yagl_marshal_get_GLsizei(out_buff);
    GLsizei height = yagl_marshal_get_GLsizei(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glViewport, GLint, GLint, GLsizei, GLsizei, x, y, width, height);
    bool res = yagl_host_glViewport(x, y, width, height);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetExtensionStringYAGL dispatcher. id = 77
 */
static bool yagl_func_glGetExtensionStringYAGL(uint8_t **out_buff,
    uint8_t *in_buff)
{
    target_ulong str = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glGetExtensionStringYAGL, target_ulong, str);
    GLuint retval;
    bool res = yagl_host_glGetExtensionStringYAGL(&retval, str);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLuint, retval);
    yagl_marshal_put_GLuint(&in_buff, retval);
    return true;
}

/*
 * glGetVertexAttribRangeYAGL dispatcher. id = 78
 */
static bool yagl_func_glGetVertexAttribRangeYAGL(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    GLenum type = yagl_marshal_get_GLenum(out_buff);
    target_ulong indices = yagl_marshal_get_ptr(out_buff);
    target_ulong range_first = yagl_marshal_get_ptr(out_buff);
    target_ulong range_count = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glGetVertexAttribRangeYAGL, GLsizei, GLenum, target_ulong, target_ulong, target_ulong, count, type, indices, range_first, range_count);
    bool res = yagl_host_glGetVertexAttribRangeYAGL(count, type, indices, range_first, range_count);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glAttachShader dispatcher. id = 79
 */
static bool yagl_func_glAttachShader(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    GLuint shader = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glAttachShader, GLuint, GLuint, program, shader);
    bool res = yagl_host_glAttachShader(program, shader);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBindAttribLocation dispatcher. id = 80
 */
static bool yagl_func_glBindAttribLocation(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    GLuint index = yagl_marshal_get_GLuint(out_buff);
    target_ulong name = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glBindAttribLocation, GLuint, GLuint, target_ulong, program, index, name);
    bool res = yagl_host_glBindAttribLocation(program, index, name);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glBlendColor dispatcher. id = 81
 */
static bool yagl_func_glBlendColor(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLclampf red = yagl_marshal_get_GLclampf(out_buff);
    GLclampf green = yagl_marshal_get_GLclampf(out_buff);
    GLclampf blue = yagl_marshal_get_GLclampf(out_buff);
    GLclampf alpha = yagl_marshal_get_GLclampf(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glBlendColor, GLclampf, GLclampf, GLclampf, GLclampf, red, green, blue, alpha);
    bool res = yagl_host_glBlendColor(red, green, blue, alpha);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glCompileShader dispatcher. id = 82
 */
static bool yagl_func_glCompileShader(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint shader = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glCompileShader, GLuint, shader);
    bool res = yagl_host_glCompileShader(shader);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glCreateProgram dispatcher. id = 83
 */
static bool yagl_func_glCreateProgram(uint8_t **out_buff,
    uint8_t *in_buff)
{
    YAGL_LOG_FUNC_ENTER_SPLIT0(glCreateProgram);
    GLuint retval;
    bool res = yagl_host_glCreateProgram(&retval);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLuint, retval);
    yagl_marshal_put_GLuint(&in_buff, retval);
    return true;
}

/*
 * glCreateShader dispatcher. id = 84
 */
static bool yagl_func_glCreateShader(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum type = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glCreateShader, GLenum, type);
    GLuint retval;
    bool res = yagl_host_glCreateShader(&retval, type);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLuint, retval);
    yagl_marshal_put_GLuint(&in_buff, retval);
    return true;
}

/*
 * glDeleteProgram dispatcher. id = 85
 */
static bool yagl_func_glDeleteProgram(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDeleteProgram, GLuint, program);
    bool res = yagl_host_glDeleteProgram(program);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDeleteShader dispatcher. id = 86
 */
static bool yagl_func_glDeleteShader(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint shader = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDeleteShader, GLuint, shader);
    bool res = yagl_host_glDeleteShader(shader);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDetachShader dispatcher. id = 87
 */
static bool yagl_func_glDetachShader(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    GLuint shader = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glDetachShader, GLuint, GLuint, program, shader);
    bool res = yagl_host_glDetachShader(program, shader);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glDisableVertexAttribArray dispatcher. id = 88
 */
static bool yagl_func_glDisableVertexAttribArray(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint index = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glDisableVertexAttribArray, GLuint, index);
    bool res = yagl_host_glDisableVertexAttribArray(index);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glEnableVertexAttribArray dispatcher. id = 89
 */
static bool yagl_func_glEnableVertexAttribArray(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint index = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glEnableVertexAttribArray, GLuint, index);
    bool res = yagl_host_glEnableVertexAttribArray(index);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetActiveAttrib dispatcher. id = 90
 */
static bool yagl_func_glGetActiveAttrib(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    GLuint index = yagl_marshal_get_GLuint(out_buff);
    GLsizei bufsize = yagl_marshal_get_GLsizei(out_buff);
    target_ulong length = yagl_marshal_get_ptr(out_buff);
    target_ulong size = yagl_marshal_get_ptr(out_buff);
    target_ulong type = yagl_marshal_get_ptr(out_buff);
    target_ulong name = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT7(glGetActiveAttrib, GLuint, GLuint, GLsizei, target_ulong, target_ulong, target_ulong, target_ulong, program, index, bufsize, length, size, type, name);
    bool res = yagl_host_glGetActiveAttrib(program, index, bufsize, length, size, type, name);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetActiveUniform dispatcher. id = 91
 */
static bool yagl_func_glGetActiveUniform(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    GLuint index = yagl_marshal_get_GLuint(out_buff);
    GLsizei bufsize = yagl_marshal_get_GLsizei(out_buff);
    target_ulong length = yagl_marshal_get_ptr(out_buff);
    target_ulong size = yagl_marshal_get_ptr(out_buff);
    target_ulong type = yagl_marshal_get_ptr(out_buff);
    target_ulong name = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT7(glGetActiveUniform, GLuint, GLuint, GLsizei, target_ulong, target_ulong, target_ulong, target_ulong, program, index, bufsize, length, size, type, name);
    bool res = yagl_host_glGetActiveUniform(program, index, bufsize, length, size, type, name);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetAttachedShaders dispatcher. id = 92
 */
static bool yagl_func_glGetAttachedShaders(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    GLsizei maxcount = yagl_marshal_get_GLsizei(out_buff);
    target_ulong count = yagl_marshal_get_ptr(out_buff);
    target_ulong shaders = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glGetAttachedShaders, GLuint, GLsizei, target_ulong, target_ulong, program, maxcount, count, shaders);
    bool res = yagl_host_glGetAttachedShaders(program, maxcount, count, shaders);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetAttribLocation dispatcher. id = 93
 */
static bool yagl_func_glGetAttribLocation(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    target_ulong name = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetAttribLocation, GLuint, target_ulong, program, name);
    int retval;
    bool res = yagl_host_glGetAttribLocation(&retval, program, name);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(int, retval);
    yagl_marshal_put_int(&in_buff, retval);
    return true;
}

/*
 * glGetProgramiv dispatcher. id = 94
 */
static bool yagl_func_glGetProgramiv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetProgramiv, GLuint, GLenum, target_ulong, program, pname, params);
    bool res = yagl_host_glGetProgramiv(program, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetProgramInfoLog dispatcher. id = 95
 */
static bool yagl_func_glGetProgramInfoLog(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    GLsizei bufsize = yagl_marshal_get_GLsizei(out_buff);
    target_ulong length = yagl_marshal_get_ptr(out_buff);
    target_ulong infolog = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glGetProgramInfoLog, GLuint, GLsizei, target_ulong, target_ulong, program, bufsize, length, infolog);
    bool res = yagl_host_glGetProgramInfoLog(program, bufsize, length, infolog);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetShaderiv dispatcher. id = 96
 */
static bool yagl_func_glGetShaderiv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint shader = yagl_marshal_get_GLuint(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetShaderiv, GLuint, GLenum, target_ulong, shader, pname, params);
    bool res = yagl_host_glGetShaderiv(shader, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetShaderInfoLog dispatcher. id = 97
 */
static bool yagl_func_glGetShaderInfoLog(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint shader = yagl_marshal_get_GLuint(out_buff);
    GLsizei bufsize = yagl_marshal_get_GLsizei(out_buff);
    target_ulong length = yagl_marshal_get_ptr(out_buff);
    target_ulong infolog = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glGetShaderInfoLog, GLuint, GLsizei, target_ulong, target_ulong, shader, bufsize, length, infolog);
    bool res = yagl_host_glGetShaderInfoLog(shader, bufsize, length, infolog);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetShaderPrecisionFormat dispatcher. id = 98
 */
static bool yagl_func_glGetShaderPrecisionFormat(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum shadertype = yagl_marshal_get_GLenum(out_buff);
    GLenum precisiontype = yagl_marshal_get_GLenum(out_buff);
    target_ulong range = yagl_marshal_get_ptr(out_buff);
    target_ulong precision = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glGetShaderPrecisionFormat, GLenum, GLenum, target_ulong, target_ulong, shadertype, precisiontype, range, precision);
    bool res = yagl_host_glGetShaderPrecisionFormat(shadertype, precisiontype, range, precision);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetShaderSource dispatcher. id = 99
 */
static bool yagl_func_glGetShaderSource(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint shader = yagl_marshal_get_GLuint(out_buff);
    GLsizei bufsize = yagl_marshal_get_GLsizei(out_buff);
    target_ulong length = yagl_marshal_get_ptr(out_buff);
    target_ulong source = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glGetShaderSource, GLuint, GLsizei, target_ulong, target_ulong, shader, bufsize, length, source);
    bool res = yagl_host_glGetShaderSource(shader, bufsize, length, source);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetUniformfv dispatcher. id = 100
 */
static bool yagl_func_glGetUniformfv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    GLint location = yagl_marshal_get_GLint(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetUniformfv, GLuint, GLint, target_ulong, program, location, params);
    bool res = yagl_host_glGetUniformfv(program, location, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetUniformiv dispatcher. id = 101
 */
static bool yagl_func_glGetUniformiv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    GLint location = yagl_marshal_get_GLint(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetUniformiv, GLuint, GLint, target_ulong, program, location, params);
    bool res = yagl_host_glGetUniformiv(program, location, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetUniformLocation dispatcher. id = 102
 */
static bool yagl_func_glGetUniformLocation(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    target_ulong name = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glGetUniformLocation, GLuint, target_ulong, program, name);
    int retval;
    bool res = yagl_host_glGetUniformLocation(&retval, program, name);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(int, retval);
    yagl_marshal_put_int(&in_buff, retval);
    return true;
}

/*
 * glGetVertexAttribfv dispatcher. id = 103
 */
static bool yagl_func_glGetVertexAttribfv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint index = yagl_marshal_get_GLuint(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetVertexAttribfv, GLuint, GLenum, target_ulong, index, pname, params);
    bool res = yagl_host_glGetVertexAttribfv(index, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetVertexAttribiv dispatcher. id = 104
 */
static bool yagl_func_glGetVertexAttribiv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint index = yagl_marshal_get_GLuint(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong params = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetVertexAttribiv, GLuint, GLenum, target_ulong, index, pname, params);
    bool res = yagl_host_glGetVertexAttribiv(index, pname, params);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glGetVertexAttribPointerv dispatcher. id = 105
 */
static bool yagl_func_glGetVertexAttribPointerv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint index = yagl_marshal_get_GLuint(out_buff);
    GLenum pname = yagl_marshal_get_GLenum(out_buff);
    target_ulong pointer = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glGetVertexAttribPointerv, GLuint, GLenum, target_ulong, index, pname, pointer);
    bool res = yagl_host_glGetVertexAttribPointerv(index, pname, pointer);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glIsProgram dispatcher. id = 106
 */
static bool yagl_func_glIsProgram(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsProgram, GLuint, program);
    GLboolean retval;
    bool res = yagl_host_glIsProgram(&retval, program);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, retval);
    yagl_marshal_put_GLboolean(&in_buff, retval);
    return true;
}

/*
 * glIsShader dispatcher. id = 107
 */
static bool yagl_func_glIsShader(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint shader = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glIsShader, GLuint, shader);
    GLboolean retval;
    bool res = yagl_host_glIsShader(&retval, shader);
    if (!res) {
        YAGL_LOG_FUNC_EXIT(NULL);
        return false;
    }
    YAGL_LOG_FUNC_EXIT_SPLIT(GLboolean, retval);
    yagl_marshal_put_GLboolean(&in_buff, retval);
    return true;
}

/*
 * glLinkProgram dispatcher. id = 108
 */
static bool yagl_func_glLinkProgram(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glLinkProgram, GLuint, program);
    bool res = yagl_host_glLinkProgram(program);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glReleaseShaderCompiler dispatcher. id = 109
 */
static bool yagl_func_glReleaseShaderCompiler(uint8_t **out_buff,
    uint8_t *in_buff)
{
    YAGL_LOG_FUNC_ENTER_SPLIT0(glReleaseShaderCompiler);
    bool res = yagl_host_glReleaseShaderCompiler();
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glShaderBinary dispatcher. id = 110
 */
static bool yagl_func_glShaderBinary(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLsizei n = yagl_marshal_get_GLsizei(out_buff);
    target_ulong shaders = yagl_marshal_get_ptr(out_buff);
    GLenum binaryformat = yagl_marshal_get_GLenum(out_buff);
    target_ulong binary = yagl_marshal_get_ptr(out_buff);
    GLsizei length = yagl_marshal_get_GLsizei(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glShaderBinary, GLsizei, target_ulong, GLenum, target_ulong, GLsizei, n, shaders, binaryformat, binary, length);
    bool res = yagl_host_glShaderBinary(n, shaders, binaryformat, binary, length);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glShaderSource dispatcher. id = 111
 */
static bool yagl_func_glShaderSource(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint shader = yagl_marshal_get_GLuint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    target_ulong string = yagl_marshal_get_ptr(out_buff);
    target_ulong length = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glShaderSource, GLuint, GLsizei, target_ulong, target_ulong, shader, count, string, length);
    bool res = yagl_host_glShaderSource(shader, count, string, length);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glStencilFuncSeparate dispatcher. id = 112
 */
static bool yagl_func_glStencilFuncSeparate(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum face = yagl_marshal_get_GLenum(out_buff);
    GLenum func = yagl_marshal_get_GLenum(out_buff);
    GLint ref = yagl_marshal_get_GLint(out_buff);
    GLuint mask = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glStencilFuncSeparate, GLenum, GLenum, GLint, GLuint, face, func, ref, mask);
    bool res = yagl_host_glStencilFuncSeparate(face, func, ref, mask);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glStencilMaskSeparate dispatcher. id = 113
 */
static bool yagl_func_glStencilMaskSeparate(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum face = yagl_marshal_get_GLenum(out_buff);
    GLuint mask = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glStencilMaskSeparate, GLenum, GLuint, face, mask);
    bool res = yagl_host_glStencilMaskSeparate(face, mask);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glStencilOpSeparate dispatcher. id = 114
 */
static bool yagl_func_glStencilOpSeparate(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLenum face = yagl_marshal_get_GLenum(out_buff);
    GLenum fail = yagl_marshal_get_GLenum(out_buff);
    GLenum zfail = yagl_marshal_get_GLenum(out_buff);
    GLenum zpass = yagl_marshal_get_GLenum(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glStencilOpSeparate, GLenum, GLenum, GLenum, GLenum, face, fail, zfail, zpass);
    bool res = yagl_host_glStencilOpSeparate(face, fail, zfail, zpass);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform1f dispatcher. id = 115
 */
static bool yagl_func_glUniform1f(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLfloat x = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform1f, GLint, GLfloat, location, x);
    bool res = yagl_host_glUniform1f(location, x);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform1fv dispatcher. id = 116
 */
static bool yagl_func_glUniform1fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    target_ulong v = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform1fv, GLint, GLsizei, target_ulong, location, count, v);
    bool res = yagl_host_glUniform1fv(location, count, v);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform1i dispatcher. id = 117
 */
static bool yagl_func_glUniform1i(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLint x = yagl_marshal_get_GLint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glUniform1i, GLint, GLint, location, x);
    bool res = yagl_host_glUniform1i(location, x);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform1iv dispatcher. id = 118
 */
static bool yagl_func_glUniform1iv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    target_ulong v = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform1iv, GLint, GLsizei, target_ulong, location, count, v);
    bool res = yagl_host_glUniform1iv(location, count, v);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform2f dispatcher. id = 119
 */
static bool yagl_func_glUniform2f(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLfloat x = yagl_marshal_get_GLfloat(out_buff);
    GLfloat y = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform2f, GLint, GLfloat, GLfloat, location, x, y);
    bool res = yagl_host_glUniform2f(location, x, y);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform2fv dispatcher. id = 120
 */
static bool yagl_func_glUniform2fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    target_ulong v = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform2fv, GLint, GLsizei, target_ulong, location, count, v);
    bool res = yagl_host_glUniform2fv(location, count, v);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform2i dispatcher. id = 121
 */
static bool yagl_func_glUniform2i(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLint x = yagl_marshal_get_GLint(out_buff);
    GLint y = yagl_marshal_get_GLint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform2i, GLint, GLint, GLint, location, x, y);
    bool res = yagl_host_glUniform2i(location, x, y);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform2iv dispatcher. id = 122
 */
static bool yagl_func_glUniform2iv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    target_ulong v = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform2iv, GLint, GLsizei, target_ulong, location, count, v);
    bool res = yagl_host_glUniform2iv(location, count, v);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform3f dispatcher. id = 123
 */
static bool yagl_func_glUniform3f(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLfloat x = yagl_marshal_get_GLfloat(out_buff);
    GLfloat y = yagl_marshal_get_GLfloat(out_buff);
    GLfloat z = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glUniform3f, GLint, GLfloat, GLfloat, GLfloat, location, x, y, z);
    bool res = yagl_host_glUniform3f(location, x, y, z);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform3fv dispatcher. id = 124
 */
static bool yagl_func_glUniform3fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    target_ulong v = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform3fv, GLint, GLsizei, target_ulong, location, count, v);
    bool res = yagl_host_glUniform3fv(location, count, v);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform3i dispatcher. id = 125
 */
static bool yagl_func_glUniform3i(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLint x = yagl_marshal_get_GLint(out_buff);
    GLint y = yagl_marshal_get_GLint(out_buff);
    GLint z = yagl_marshal_get_GLint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glUniform3i, GLint, GLint, GLint, GLint, location, x, y, z);
    bool res = yagl_host_glUniform3i(location, x, y, z);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform3iv dispatcher. id = 126
 */
static bool yagl_func_glUniform3iv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    target_ulong v = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform3iv, GLint, GLsizei, target_ulong, location, count, v);
    bool res = yagl_host_glUniform3iv(location, count, v);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform4f dispatcher. id = 127
 */
static bool yagl_func_glUniform4f(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLfloat x = yagl_marshal_get_GLfloat(out_buff);
    GLfloat y = yagl_marshal_get_GLfloat(out_buff);
    GLfloat z = yagl_marshal_get_GLfloat(out_buff);
    GLfloat w = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glUniform4f, GLint, GLfloat, GLfloat, GLfloat, GLfloat, location, x, y, z, w);
    bool res = yagl_host_glUniform4f(location, x, y, z, w);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform4fv dispatcher. id = 128
 */
static bool yagl_func_glUniform4fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    target_ulong v = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform4fv, GLint, GLsizei, target_ulong, location, count, v);
    bool res = yagl_host_glUniform4fv(location, count, v);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform4i dispatcher. id = 129
 */
static bool yagl_func_glUniform4i(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLint x = yagl_marshal_get_GLint(out_buff);
    GLint y = yagl_marshal_get_GLint(out_buff);
    GLint z = yagl_marshal_get_GLint(out_buff);
    GLint w = yagl_marshal_get_GLint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glUniform4i, GLint, GLint, GLint, GLint, GLint, location, x, y, z, w);
    bool res = yagl_host_glUniform4i(location, x, y, z, w);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniform4iv dispatcher. id = 130
 */
static bool yagl_func_glUniform4iv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    target_ulong v = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glUniform4iv, GLint, GLsizei, target_ulong, location, count, v);
    bool res = yagl_host_glUniform4iv(location, count, v);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniformMatrix2fv dispatcher. id = 131
 */
static bool yagl_func_glUniformMatrix2fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    GLboolean transpose = yagl_marshal_get_GLboolean(out_buff);
    target_ulong value = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glUniformMatrix2fv, GLint, GLsizei, GLboolean, target_ulong, location, count, transpose, value);
    bool res = yagl_host_glUniformMatrix2fv(location, count, transpose, value);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniformMatrix3fv dispatcher. id = 132
 */
static bool yagl_func_glUniformMatrix3fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    GLboolean transpose = yagl_marshal_get_GLboolean(out_buff);
    target_ulong value = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glUniformMatrix3fv, GLint, GLsizei, GLboolean, target_ulong, location, count, transpose, value);
    bool res = yagl_host_glUniformMatrix3fv(location, count, transpose, value);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUniformMatrix4fv dispatcher. id = 133
 */
static bool yagl_func_glUniformMatrix4fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLint location = yagl_marshal_get_GLint(out_buff);
    GLsizei count = yagl_marshal_get_GLsizei(out_buff);
    GLboolean transpose = yagl_marshal_get_GLboolean(out_buff);
    target_ulong value = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glUniformMatrix4fv, GLint, GLsizei, GLboolean, target_ulong, location, count, transpose, value);
    bool res = yagl_host_glUniformMatrix4fv(location, count, transpose, value);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glUseProgram dispatcher. id = 134
 */
static bool yagl_func_glUseProgram(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glUseProgram, GLuint, program);
    bool res = yagl_host_glUseProgram(program);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glValidateProgram dispatcher. id = 135
 */
static bool yagl_func_glValidateProgram(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint program = yagl_marshal_get_GLuint(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT1(glValidateProgram, GLuint, program);
    bool res = yagl_host_glValidateProgram(program);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glVertexAttrib1f dispatcher. id = 136
 */
static bool yagl_func_glVertexAttrib1f(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint indx = yagl_marshal_get_GLuint(out_buff);
    GLfloat x = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glVertexAttrib1f, GLuint, GLfloat, indx, x);
    bool res = yagl_host_glVertexAttrib1f(indx, x);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glVertexAttrib1fv dispatcher. id = 137
 */
static bool yagl_func_glVertexAttrib1fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint indx = yagl_marshal_get_GLuint(out_buff);
    target_ulong values = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glVertexAttrib1fv, GLuint, target_ulong, indx, values);
    bool res = yagl_host_glVertexAttrib1fv(indx, values);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glVertexAttrib2f dispatcher. id = 138
 */
static bool yagl_func_glVertexAttrib2f(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint indx = yagl_marshal_get_GLuint(out_buff);
    GLfloat x = yagl_marshal_get_GLfloat(out_buff);
    GLfloat y = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT3(glVertexAttrib2f, GLuint, GLfloat, GLfloat, indx, x, y);
    bool res = yagl_host_glVertexAttrib2f(indx, x, y);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glVertexAttrib2fv dispatcher. id = 139
 */
static bool yagl_func_glVertexAttrib2fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint indx = yagl_marshal_get_GLuint(out_buff);
    target_ulong values = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glVertexAttrib2fv, GLuint, target_ulong, indx, values);
    bool res = yagl_host_glVertexAttrib2fv(indx, values);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glVertexAttrib3f dispatcher. id = 140
 */
static bool yagl_func_glVertexAttrib3f(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint indx = yagl_marshal_get_GLuint(out_buff);
    GLfloat x = yagl_marshal_get_GLfloat(out_buff);
    GLfloat y = yagl_marshal_get_GLfloat(out_buff);
    GLfloat z = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT4(glVertexAttrib3f, GLuint, GLfloat, GLfloat, GLfloat, indx, x, y, z);
    bool res = yagl_host_glVertexAttrib3f(indx, x, y, z);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glVertexAttrib3fv dispatcher. id = 141
 */
static bool yagl_func_glVertexAttrib3fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint indx = yagl_marshal_get_GLuint(out_buff);
    target_ulong values = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glVertexAttrib3fv, GLuint, target_ulong, indx, values);
    bool res = yagl_host_glVertexAttrib3fv(indx, values);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glVertexAttrib4f dispatcher. id = 142
 */
static bool yagl_func_glVertexAttrib4f(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint indx = yagl_marshal_get_GLuint(out_buff);
    GLfloat x = yagl_marshal_get_GLfloat(out_buff);
    GLfloat y = yagl_marshal_get_GLfloat(out_buff);
    GLfloat z = yagl_marshal_get_GLfloat(out_buff);
    GLfloat w = yagl_marshal_get_GLfloat(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT5(glVertexAttrib4f, GLuint, GLfloat, GLfloat, GLfloat, GLfloat, indx, x, y, z, w);
    bool res = yagl_host_glVertexAttrib4f(indx, x, y, z, w);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glVertexAttrib4fv dispatcher. id = 143
 */
static bool yagl_func_glVertexAttrib4fv(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint indx = yagl_marshal_get_GLuint(out_buff);
    target_ulong values = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT2(glVertexAttrib4fv, GLuint, target_ulong, indx, values);
    bool res = yagl_host_glVertexAttrib4fv(indx, values);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

/*
 * glVertexAttribPointer dispatcher. id = 144
 */
static bool yagl_func_glVertexAttribPointer(uint8_t **out_buff,
    uint8_t *in_buff)
{
    GLuint indx = yagl_marshal_get_GLuint(out_buff);
    GLint size = yagl_marshal_get_GLint(out_buff);
    GLenum type = yagl_marshal_get_GLenum(out_buff);
    GLboolean normalized = yagl_marshal_get_GLboolean(out_buff);
    GLsizei stride = yagl_marshal_get_GLsizei(out_buff);
    target_ulong ptr = yagl_marshal_get_ptr(out_buff);
    YAGL_LOG_FUNC_ENTER_SPLIT6(glVertexAttribPointer, GLuint, GLint, GLenum, GLboolean, GLsizei, target_ulong, indx, size, type, normalized, stride, ptr);
    bool res = yagl_host_glVertexAttribPointer(indx, size, type, normalized, stride, ptr);
    YAGL_LOG_FUNC_EXIT(NULL);
    return res;
}

const uint32_t yagl_gles2_api_num_funcs = 144;

yagl_api_func yagl_gles2_api_funcs[] = {
    &yagl_func_glActiveTexture,
    &yagl_func_glBindBuffer,
    &yagl_func_glBindFramebuffer,
    &yagl_func_glBindRenderbuffer,
    &yagl_func_glBindTexture,
    &yagl_func_glBlendEquation,
    &yagl_func_glBlendEquationSeparate,
    &yagl_func_glBlendFunc,
    &yagl_func_glBlendFuncSeparate,
    &yagl_func_glBufferData,
    &yagl_func_glBufferSubData,
    &yagl_func_glCheckFramebufferStatus,
    &yagl_func_glClear,
    &yagl_func_glClearColor,
    &yagl_func_glClearDepthf,
    &yagl_func_glClearStencil,
    &yagl_func_glColorMask,
    &yagl_func_glCompressedTexImage2D,
    &yagl_func_glCompressedTexSubImage2D,
    &yagl_func_glCopyTexImage2D,
    &yagl_func_glCopyTexSubImage2D,
    &yagl_func_glCullFace,
    &yagl_func_glDeleteBuffers,
    &yagl_func_glDeleteFramebuffers,
    &yagl_func_glDeleteRenderbuffers,
    &yagl_func_glDeleteTextures,
    &yagl_func_glDepthFunc,
    &yagl_func_glDepthMask,
    &yagl_func_glDepthRangef,
    &yagl_func_glDisable,
    &yagl_func_glDrawArrays,
    &yagl_func_glDrawElements,
    &yagl_func_glEGLImageTargetTexture2DOES,
    &yagl_func_glEnable,
    &yagl_func_glFinish,
    &yagl_func_glFlush,
    &yagl_func_glFramebufferTexture2D,
    &yagl_func_glFramebufferRenderbuffer,
    &yagl_func_glFrontFace,
    &yagl_func_glGenBuffers,
    &yagl_func_glGenerateMipmap,
    &yagl_func_glGenFramebuffers,
    &yagl_func_glGenRenderbuffers,
    &yagl_func_glGenTextures,
    &yagl_func_glGetBooleanv,
    &yagl_func_glGetBufferParameteriv,
    &yagl_func_glGetError,
    &yagl_func_glGetFloatv,
    &yagl_func_glGetFramebufferAttachmentParameteriv,
    &yagl_func_glGetIntegerv,
    &yagl_func_glGetRenderbufferParameteriv,
    &yagl_func_glGetTexParameterfv,
    &yagl_func_glGetTexParameteriv,
    &yagl_func_glHint,
    &yagl_func_glIsBuffer,
    &yagl_func_glIsEnabled,
    &yagl_func_glIsFramebuffer,
    &yagl_func_glIsRenderbuffer,
    &yagl_func_glIsTexture,
    &yagl_func_glLineWidth,
    &yagl_func_glPixelStorei,
    &yagl_func_glPolygonOffset,
    &yagl_func_glReadPixels,
    &yagl_func_glRenderbufferStorage,
    &yagl_func_glSampleCoverage,
    &yagl_func_glScissor,
    &yagl_func_glStencilFunc,
    &yagl_func_glStencilMask,
    &yagl_func_glStencilOp,
    &yagl_func_glTexImage2D,
    &yagl_func_glTexParameterf,
    &yagl_func_glTexParameterfv,
    &yagl_func_glTexParameteri,
    &yagl_func_glTexParameteriv,
    &yagl_func_glTexSubImage2D,
    &yagl_func_glViewport,
    &yagl_func_glGetExtensionStringYAGL,
    &yagl_func_glGetVertexAttribRangeYAGL,
    &yagl_func_glAttachShader,
    &yagl_func_glBindAttribLocation,
    &yagl_func_glBlendColor,
    &yagl_func_glCompileShader,
    &yagl_func_glCreateProgram,
    &yagl_func_glCreateShader,
    &yagl_func_glDeleteProgram,
    &yagl_func_glDeleteShader,
    &yagl_func_glDetachShader,
    &yagl_func_glDisableVertexAttribArray,
    &yagl_func_glEnableVertexAttribArray,
    &yagl_func_glGetActiveAttrib,
    &yagl_func_glGetActiveUniform,
    &yagl_func_glGetAttachedShaders,
    &yagl_func_glGetAttribLocation,
    &yagl_func_glGetProgramiv,
    &yagl_func_glGetProgramInfoLog,
    &yagl_func_glGetShaderiv,
    &yagl_func_glGetShaderInfoLog,
    &yagl_func_glGetShaderPrecisionFormat,
    &yagl_func_glGetShaderSource,
    &yagl_func_glGetUniformfv,
    &yagl_func_glGetUniformiv,
    &yagl_func_glGetUniformLocation,
    &yagl_func_glGetVertexAttribfv,
    &yagl_func_glGetVertexAttribiv,
    &yagl_func_glGetVertexAttribPointerv,
    &yagl_func_glIsProgram,
    &yagl_func_glIsShader,
    &yagl_func_glLinkProgram,
    &yagl_func_glReleaseShaderCompiler,
    &yagl_func_glShaderBinary,
    &yagl_func_glShaderSource,
    &yagl_func_glStencilFuncSeparate,
    &yagl_func_glStencilMaskSeparate,
    &yagl_func_glStencilOpSeparate,
    &yagl_func_glUniform1f,
    &yagl_func_glUniform1fv,
    &yagl_func_glUniform1i,
    &yagl_func_glUniform1iv,
    &yagl_func_glUniform2f,
    &yagl_func_glUniform2fv,
    &yagl_func_glUniform2i,
    &yagl_func_glUniform2iv,
    &yagl_func_glUniform3f,
    &yagl_func_glUniform3fv,
    &yagl_func_glUniform3i,
    &yagl_func_glUniform3iv,
    &yagl_func_glUniform4f,
    &yagl_func_glUniform4fv,
    &yagl_func_glUniform4i,
    &yagl_func_glUniform4iv,
    &yagl_func_glUniformMatrix2fv,
    &yagl_func_glUniformMatrix3fv,
    &yagl_func_glUniformMatrix4fv,
    &yagl_func_glUseProgram,
    &yagl_func_glValidateProgram,
    &yagl_func_glVertexAttrib1f,
    &yagl_func_glVertexAttrib1fv,
    &yagl_func_glVertexAttrib2f,
    &yagl_func_glVertexAttrib2fv,
    &yagl_func_glVertexAttrib3f,
    &yagl_func_glVertexAttrib3fv,
    &yagl_func_glVertexAttrib4f,
    &yagl_func_glVertexAttrib4fv,
    &yagl_func_glVertexAttribPointer
};
