/*
 * Generated by gen-yagl-calls.sh, do not modify!
 */
#ifndef _QEMU_YAGL_GLES1_CALLS_H_
#define _QEMU_YAGL_GLES1_CALLS_H_

#include "yagl_types.h"

extern const uint32_t yagl_gles1_api_num_funcs;

extern yagl_api_func yagl_gles1_api_funcs[];

#endif
