# ECS Makefile.tizen

$(call set-vpath, $(SRC_PATH):$(TARGET_PATH):$(SRC_PATH)/tizen/src/ecs:$(SRC_PATH)/tizen/src/ecs/genmsg:$(SRC_PATH)/tizen/distrib/protobuf)

QEMU_CFLAGS += -I$(SRC_PATH)/tizen/distrib/protobuf
QEMU_CFLAGS += -I$(SRC_PATH)/tizen/src/ecs/genmsg

obj-y += ecs.pb-c.o ecs_ids.pb-c.o protobuf-c.o
obj-y += ecs_msg.o ecs.o ecs_sensor.o
obj-y += ecs_mon.o ecs-json-streamer.o

# NFC message extension
obj-y += nfc.pb-c.o
