#!/bin/sh

ETC_PATH=$INSTALLED_PATH/Emulator/etc
echo $ETC_PATH
## Remove etc path
if test -e $ETC_PATH
then
	rm -rf $ETC_PATH
fi
## Register .desktop file
${REMOVE_SHORTCUT}  tizen-sdk-vtm.desktop
### END Register Menu ###

## Remove icon file ##
rm -f ~/.local/share/icons/vtm.ico
## End remove icon file ##
