#!/bin/sh -e

ETC_PATH= $INSTALLED_PATH/Emulator/etc
echo $ETC_PATH
## Remove etc path
if test -e $ETC_PATH
then
	rm -f $ETC_PATH
fi
## Register .desktop file
xdg-desktop-menu uninstall $MENU_DIRECTORY_NAME  tizen-sdk-vtm.desktop
### END Register Menu ###

## Remove icon file ##
rm -f ~/.local/share/icons/vtm.ico
## End remove icon file ##
