#!/bin/sh -e

## Register .desktop file
xdg-desktop-menu uninstall $MENU_DIRECTORY  tizen-sdk-vtm.desktop
### END Register Menu ###

## Remove icon file ##
rm -f ~/.local/share/icons/vtm.ico
## End remove icon file ##
