#!/bin/sh
### BEGIN INIT INFO
# Provides:          tizen-kvm
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Should-Start:      udev
# Should-Stop:       udev
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: modprobe kvm module.
# Description:       enable kvm module to use hardware virtualization.
### END INIT INFO

do_start () {
	if grep -qs "^flags.* vmx" /proc/cpuinfo; then
		modprobe -b kvm_intel
	elif grep -qs "^flags.* svm" /proc/cpuinfo; then
		modprobe -b kvm_amd
	fi
}

add_group () {
	# Add the kvm group unless it's already there
	if ! getent group kvm > /dev/null; then
		addgroup --quiet --system kvm || true
	fi
}

do_udev () {
	# remove group::--- acl mistakenly placed on /dev/kvm by udev-acl
	if [ -c /dev/kvm -a ! -L /dev/kvm ]
	then
		/usr/bin/setfacl -m g::rw /dev/kvm
	fi

	# udev rules for /dev/kvm have changed, so have udev recalculate
	udevadm trigger --subsystem-match=misc --action=change
}

case "$1" in
  start)
	do_start
	add_group
	do_udev
	;;
  restart|reload|force-reload)
	# No-op
	;;
  stop)
	# No-op
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
