//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.22 at 04:10:02 PM KST 
//


package org.tizen.emulator.skin.dbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rotationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rotationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lcd" type="{http://www.tizen.org/emulator/skin/dbi}lcdType"/>
 *         &lt;element name="imageList" type="{http://www.tizen.org/emulator/skin/dbi}imageListType"/>
 *         &lt;element name="keyMapList" type="{http://www.tizen.org/emulator/skin/dbi}keyMapListType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.tizen.org/emulator/skin/dbi}rotationNameType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rotationType", propOrder = {
    "lcd",
    "imageList",
    "keyMapList"
})
public class RotationType {

    @XmlElement(required = true)
    protected LcdType lcd;
    @XmlElement(required = true)
    protected ImageListType imageList;
    @XmlElement(required = true)
    protected KeyMapListType keyMapList;
    @XmlAttribute(name = "name", required = true)
    protected RotationNameType name;

    /**
     * Gets the value of the lcd property.
     * 
     * @return
     *     possible object is
     *     {@link LcdType }
     *     
     */
    public LcdType getLcd() {
        return lcd;
    }

    /**
     * Sets the value of the lcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link LcdType }
     *     
     */
    public void setLcd(LcdType value) {
        this.lcd = value;
    }

    /**
     * Gets the value of the imageList property.
     * 
     * @return
     *     possible object is
     *     {@link ImageListType }
     *     
     */
    public ImageListType getImageList() {
        return imageList;
    }

    /**
     * Sets the value of the imageList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageListType }
     *     
     */
    public void setImageList(ImageListType value) {
        this.imageList = value;
    }

    /**
     * Gets the value of the keyMapList property.
     * 
     * @return
     *     possible object is
     *     {@link KeyMapListType }
     *     
     */
    public KeyMapListType getKeyMapList() {
        return keyMapList;
    }

    /**
     * Sets the value of the keyMapList property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyMapListType }
     *     
     */
    public void setKeyMapList(KeyMapListType value) {
        this.keyMapList = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link RotationNameType }
     *     
     */
    public RotationNameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link RotationNameType }
     *     
     */
    public void setName(RotationNameType value) {
        this.name = value;
    }

}
